import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          "OUT_APP_TIP": "再按一次退出应用",
          "SET_ACCOUNT": "账户",
          "GUAN_ZHU": "关注",
          "QU_SHI": "趋势 24h",
          "MENU_THEME": "外观",
          "MENU_LOCAL": "多语言",
          "SET_THEME": "设置主题",
          "THEME_AUTO": "跟随系统",
          "THEME_LIGHT": "浅色",
          "THEME_DARK": "深色",
          "SET_LOCAL": "设置语言",
          "EN_US": "英文",
          "ZH_CN": "简体中文",
          "ZH_TW": "繁体中文",
          "JA_JP": "日语",
          "TH_TH": "泰语",
          "FR_CH": "法语",
          "PT_BR": "葡萄牙语",
          "TIAO": "条",
          "YONG_HU": "用户",
          "YI_QJRZYY_ZHOU": "一起进入自由宇宙",
          "XING_Q_LIU": "星期六",
          "QING_SRHYB_ZHU": "请输入好友备注",
          "TUI_C_D_LU": "退出登录",
          "QU_X_G_ZHU": "取消关注",
          "ZHONG_XU_QI_DESC":
              "中继器就像服务器，用来存储和检索数据。Freerse客户端创建在Nostr上的， Nostr是去中心化的，并且有许多中继器提供数据储存和检索服务。你添加了多少中继器，你的数据就会传输备份在多少中继器上，你可以添加你喜欢的中继器。",
          "TIAN_JIA": "添加",
          "COPY_DESC": "任何违反本 EULA 的行为，包括上述禁止的内容 和行为，都可能导致您对我们的应用程序的访问 被终止。",
          "CHUANG_JNDZ_HU": "创建你的账户",
          "SI_YUE": "私钥",
          "TIAN_JNDSDQBD_ZHI": "添加你的闪电钱包地址",
          "TOU_XIANG": "头像",
          "TIAN_JNDRZW_ZHI": "添加你的NIP-05认证网址",
          "WO": "我",
          "BAO_CUN": "保存",
          "QING_ZZLSRB_TI": "请在这里输入标题",
          "ZHANG_HAO": "账号: ",
          "CU_ZDN_RONG": "促进使用或销售非法或管制物质、烟草制品、弹药和/或枪支的内容；",
          "ZAI_NDGRZLZTJJ_JIE": "在你的个人资料中添加简介",
          "TONG_ZHI": "通知",
          "DI_ZHI": "地址",
          "YONG_H_MING": "用户名",
          "JIA_RHM_DAN": "加入黑名单",
          "XING_Q_ER": "星期二",
          "NI_YSCZGZJQ_MA": "你要删除这个中继器吗?",
          "SHU_YNZJDSJW_LUO": "属于你自己的社交网络",
          "LA_HEI": "屏蔽用户",
          "YI_Z_FA": "已转发",
          "ZHANG_HMMS_YUE": "账户密码私钥",
          "ZE_REN": "责任",
          "TIAN": "天",
          "ZHUAN_ZHANG": "转账",
          "MING_ZBNW_KONG": "名字不能为空",
          "SHU_RZJQDD_ZHI": "输入中继器的地址",
          "TIAN_JNDM_ZI": "添加你的名字",
          "DENG_LU": "登录",
          "WEN_ZHANG": "文章",
          "XING_Q_WU": "星期五",
          "NONE_ZZYHXKXY_NONE": "《最终用户许可协议》",
          "ZHANG_HG_YUE_1": "账户ID公钥",
          "YI_CSC_JIA": "移除收藏夹",
          "SAO_Y_S_MA": "扫一扫码",
          "YI_TJZJ_QI": "已添加中继器",
          "FU_ZTW_NONE": "复制帖子ID",
          "C_DELETE": "删除",
          "TIAN_JFMTPCCW_NONE": "添加封面图片尺寸为 2.35:1",
          "FA_Q_Q_LIAO": "发起群聊",
          "FEN_ZHONG": "分钟",
          "FU_Z_C_GONG": "复制成功！",
          "SHOU_CANG": "收藏",
          "FA_BU": "发布",
          "FA_SONG": "发送",
          "BIAO_QIAN": "标签",
          "KONG_HWXMCSRHQLTRSHWCN_REN": "* 恐吓威胁、冒充、骚扰或欺凌他人，伤害未成年人;",
          "SHOU_D_NONE": "收到 500 SAT",
          "SHE_Z_B_ZHU": "设置备注",
          "BIAO_JWCWZ_NONE": "标记为长文章√",
          "WEI_G_H_GUO": "违规后果",
          "SHE_ZHI": "设置",
          "CHI_C_NONE": "尺寸 2.5:1",
          "XUAN_ZWZL_XING": "选择文章类型",
          "GE_R_Z_LIAO": "个人资料",
          "TUI_W_X_QING": "Freerse详情",
          "TI_SHI": "提示",
          "QIAN_BAO": "钱包",
          "ZUI_ZYHXKX_YI": "最终用户许可协议 ",
          "DIAN_JI": "Zap",
          "SHAN_D_F_PIAO": "闪电发票",
          "SHAN_DQBD_ZHI": "闪电钱包地址",
          "CONG": "聪",
          "SAO_Y_SAO": "扫一扫",
          "JIN_ZNRHX_WEI": "禁止内容和行为 ",
          "YU_DBYGDFFN_RONG": "* 与赌博有关的非法内容;",
          "WO_D_S_CANG": "我的收藏",
          "XING_Q_SI": "星期四",
          "QU_XIAO": "取消",
          "BAN_B_NONE": "版本",
          "TIAN_JXDZJ_QI": "添加新的中继器",
          "ZHONG_J_QI": "中继器",
          "REN_MEN": "人们",
          "QUAN_Q_T_WEN": "全球",
          "ZHENG_C_F_BU": "正常发布",
          "COPY_DESC_10": "* 侵犯任何第三方权利的内容，包括版权、商标、隐私、宣传或其他个人或专有权利，或者具有欺骗性或欺诈性；",
          "HUI_FU_2": "回复:",
          "TIAN_JZYB_JING": "添加主页背景",
          "TUI_W_LIAN": "Freerse链",
          "LIAN_X_REN": "联系人",
          "ZHI_FU": "支付",
          "TIE_ZJTBDWZX_SHI": "帖子将同步到文章显示",
          "BAO_LIU_QUANLI":
              "我们保留随时修改本 EULA 的权利，恕不另行通知。您在发布任何修改后的 EULA 后继续使用该应用程序表明您接受修改后的 EULA 的条款。",
          "TONG_YBJ_XU": "同意并继续",
          "XING_Q_TIAN": "星期日",
          "SOU_SUO": "搜索",
          "REN_ZHENG": "认证",
          "PRI_DESC":
              "私钥是你的账户密码，如果你丢失了你的私钥，你将无法 访问你的账户！私钥没有办法找回，保存好你的私钥，千万不要透露给任何人。",
          "TIAN_JNDW_ZHAN": "添加你的网站",
          "TUI_WYH_FU": "回复",
          "WEN_ZDYX_XI": "文章订阅消息",
          "COPY_DESC_12":
              "本最终用户许可协议（“EULA”）是您与Freerse Inc. 之间关于使用移动应用程序 Freerse 的法律协议。通过安装、访问或使用我们的应用程序，您同意受本 EULA 的条款和条件的约束。如果您不同意本 EULA，则不得使用我们的应用程序。",
          "TIAN_XNDZHS_YUE": "填写你的账户私钥",
          "CHUANG_J_Z_HU": "创建",
          "QING_XTYX_YI": "请先同意协议",
          "TIAN_JDSC_JIA": "添加到收藏夹",
          "XING_Q_SAN": "星期三",
          "FU_ZYHG_YUE": "复制用户ID公钥",
          "WANG_ZHAN": "网站",
          "LA_HCY_HU": "拉黑此用户",
          "SOU_S_NONE": "搜索Freeres",
          "XING_Q_YI": "星期一",
          "ZHANG_HG_YUE": "账户ID公钥",
          "YI_YDBT_YI": "已阅读并同意",
          "WO_YJBCLWDMMS_YUE": "我已经保存了我的密码私钥",
          "SHOU_F_KUAN": "收付款 ",
          "FU_Z_W_BEN": "复制文本",
          "GONG_YUE": "公钥",
          "COPY_DESC_11":
              "我们的应用程序“按原样”和“可用”提供，不提供任何明示或暗示的保证，包括但不限于对适销性和特定用途适用性的暗示保证。我们不保证我们的应用程序不会中断或没有错误。在任何情况下，Freerse Inc. 均不对因使用或无法使用我们的应用程序而引起或与之相关的任何损害承担责任，包括但不限于直接、间接、特殊、附带或后果性损害。",
          "ZUO_TIAN": "昨天 ",
          "DAI_YQSXSDBLXYCHY_LUN": "* 带有歧视性、煽动暴力、宣扬仇恨言论；",
          "NIN_TYBJYYJZDNRHXWBKDBX_YU": "您同意不将 Freerse 用于禁止的内容或行为，包括但不限于",
          "TIAN_J_F_WU": "添加服务",
          "SHUO_DSM_BA": "说点什么吧...",
          "FEN_SI": "粉丝",
          "BIAN_JGRZ_LIAO": "编辑资料",
          "BANG_Z_Z_XIN": "帮助中心",
          "KAI_SHI": "开始",
          "YIN_HSQMFFBZSBLHHFFNRHX_DU": "* 淫秽、色情、冒犯、诽谤、中伤、暴力和/或非法内容或亵渎；",
          "ZI_L_S_ZHI": "资料设置",
          "ZXQ_DI_QI":
              "第一排绿色的圆点是代表中继器的网络信号强弱，绿色是流畅，红色是信号较弱。第二排的图标中有Bitcoin的图标的是付费中继器.",
          "TIAN_S_RU": "添输入",
          "ZHU_YBJ_TU": "主页背景图",
          "FU_ZYHGY_NONE": "复制用户公钥 Pubkey",
          "CONG_ZLKSXZ_WEN": "从这里开始写正文",
          "DIAN_ZAN": "点赞",
          "XIAO_SHI": "小时",
          "GUAN_Y_WO": "关于我",
          "ZHAO_PIAN": "照片",
          "BAO_CNDS_YUE": "保存你的私钥",
          "BIAO_ZWCW_ZHANG": "标注为长文章",
          "MIAO": "秒",
          "YU_LAN": "预览",
          "QU_X_L_HEI": "取消拉黑",
          "RU_GNDCYRHYWQTGYWML_XI":
              "如果您对此 EULA 有任何疑问，请通过freerse8@gmail.com与我们联系。",
          "TIAN_JNDYH_MING": "添加你的用户名",
          "JIE_S_T_KUAN": "接受条款",
          "BIAO_JWTW_NONE": "正常发布",
          "ZHI_D_L_TIAN": "置顶聊天",
          "JIE_SHOU": "接受",
          "GUAN_ZHU": "关注",
          "MING_ZI": "名字",
          "HUI_FU": "回复",
          "LISENCE_ACCEPT_DESC1":
              "使用我们的应用程序即表示您接受本EULA。如果您不同意本EULA，您不得使用我们的应用程序。",
          "QING_XQRYJBCMMS_YUE": "请先确认已经保存密码私钥",
          "XIAO_XI": "消息",
          "LIAN_X_F_SHI": "联系方式",
          "BA_TTJGP_YOU": "把他推荐给朋友",
          "TIAN_J_C_GONG": "添加成功！",
          "ZHUAN_FA": "转发",
          "FA_XIAN": "发现",
          "GUAN_Y_NONE": "关于Freerse",
          "XIN_D_P_YOU": "新的朋友",
          "GONG_YSNGZ_NI": "公钥是你的账户ID，你可以复制发送给你的朋友，他可以通过公钥搜索关注你。",
          "BIAN_G_NONE": "变更EULA",
          "NIP_AUTH": "NIP-05认证",
          "JUBAO": "举报",
          "JUBAO_OK": "举报成功",
          "JUBAO_LJ": "垃圾内容",
          "JUBAO_LT": "裸体或暴露的内容",
          "JUBAO_WG": "违规内容",
          "DELETE_ACCOUNT": "删除账户",
          "DELETE_ACCOUNT_TIP": "你将删除你的账户信息，你会失去你的账户所有信息，你确定要继续删除账户吗？",
          "SHOW_MORE": "显示更多",
          "ZAP_WALLET": "闪电钱包",
          "IMAGE": "图片",
          "ZAP_CONNECT_TIP":
              "粘贴或输入公钥、Relay、Wallet Connect Secret,只支持适配了Nostr Wallet Connect协议的钱包。",
          "PASTE_OR_ENTER_HERE": "请在这里粘贴或输入",
          "PASTE": "粘贴",
          "CLEAR": "清除",
          "CONNECT_WALLET": "连接钱包",
          "SCAN_QR_CODE": "扫描二维码",
          "CONNECT_OTHER_WALLETS": "连接其他钱包",
          "OTHER_AMOUNT": "其他金额",
          "PLEASE_INPUT_AMOUNT": "请输入数量",
          "MESSAGE": "留言",
          "PLEASE_INPUT_MESSAGE": "请输入留言",
          "CONFIRM": "确定",
          "DEFAULT_ZAP_AMOUNT_IN_SATS": "默认Zap金额，以sat为单位。",
          "ZAP_AMOUNT_TIP":
              "1个比特币=100,000,000 sats，点击Zap发送默认金额，长按Zap按钮可以发送自定义金额。",
          "SET_CUSTOM_ZAP_AMOUNT": "设置自定义Zap金额",
          "RESTORE_DEFAULT_SETTINGS": "恢复默认设置",
          "ZAP_AMOUNT_SETTINGS": "Zap金额设置",
          "BITCOIN_LIGHTNING_WALLET": "比特币闪电钱包",
          "ZAP_RECEIVE_SEND_TIP": "发送和接受Zap,请连接一个比特币闪电钱包。",
          "ZAP_DES": "Zap就是用比特币打赏你喜欢的帖子。",
          "ALBY_BITCOIN_LIGHTNING_WALLET_IS_CONNECTED": "已连接Alby比特币闪电钱包",
          "BITCOIN_LIGHTNING_WALLET_IS_CONNECTED": "已连接比特币闪电钱包",
          "DISCONNECT_WALLET": "断连钱包",
          "CONNECT_ALBY_WALLET": "连接Alby钱包",
          "DISCONNECT_TIP": "断连钱包将无法发送zap，此钱包地址还可以接收zap，如需要修改钱包地址，请在个人资料中修改。",
          "ZAP_SENDING": "Zap发送中",
          "NO_WALLET_WAS_FOUND": "没有找到钱包。",
          "THIS_ACCOUNT_DOES_NOT_HAVE_A_WALLET_ADDRESS_SET": "此账户没有设置钱包地址。",
          "QUOTE": "引用",
          "DONATE": "捐赠",
          "DONATE_DES1": "支持Freerse",
          "DONATE_DES2": "帮助建造去中心化的社交网络。",
          "RETWEETED": "转发了",
          "ZAPED": "打闪了",
          "REACTED": "点赞了",
          "AND": "和",
          "OTHERS": "其他人",
          "YOUR_FREERSE": "你的freerse",
          "YOU": "你",
          "H_Y_S_Q_X_X": "好友申请消息",
          "SAVE_IMAGE_SUCCESS": "已保存到相册",
          "LOADING": "加载中",
          "FAILED_TO_SEND": "发送失败",
          "THANKS_DONATE": "感谢捐赠",
          "ZAP_FAIL": "Zap失败",
          "DONATE1_NAME": "Freerse 捐赠 1",
          "DONATE2_NAME": "Freerse 捐赠 2",
          "DONATE3_NAME": "Freerse 捐赠 3",
          "DONATE4_NAME": "Freerse 捐赠 4",
          "COPY": "复制",
          "HOT": "热门"
        },
        'zh_TW': {
          "OUT_APP_TIP": "再按一次退出应用",
          "SET_ACCOUNT": "帳號",
          "GUAN_ZHU": "關注",
          "QU_SHI": "趨勢 24h",
          "MENU_THEME": "外觀",
          "MENU_LOCAL": "多語言",
          "SET_THEME": "設定主題",
          "THEME_AUTO": "跟隨系統",
          "THEME_LIGHT": "淺色",
          "THEME_DARK": "深色",
          "SET_LOCAL": "設定語言",
          "EN_US": "英文",
          "ZH_CN": "簡體中文",
          "ZH_TW": "繁體中文",
          "JA_JP": "日文",
          "TH_TH": "泰語",
          "FR_CH": "法文",
          "PT_BR": "葡萄牙語",
          "TIAO": "條",
          "YONG_HU": "用戶",
          "YI_QJRZYY_ZHOU": "一起進入自由宇宙",
          "XING_Q_LIU": "星期六",
          "QING_SRHYB_ZHU": "請輸入好友備註",
          "TUI_C_D_LU": "退出登錄",
          "QU_X_G_ZHU": "取消關注",
          "ZHONG_XU_QI_DESC":
              "中繼器就像服務器，用來存儲和檢索數據。Freerse客戶端創建在Nostr上的， Nostr是去中心化的，並且有許多中繼器提供數據儲存和檢索服務。你添加了多少中繼器，你的數據就會傳輸備份在多少中繼器上，你可以添加你喜歡的中繼器。",
          "TIAN_JIA": "添加",
          "COPY_DESC": "任何違反本 EULA 的行為，包括上述禁止的內容 和行為，都可能導致您對我們的應用程序的訪問 被終止。",
          "CHUANG_JNDZ_HU": "創建你的賬戶",
          "SI_YUE": "私鑰",
          "TIAN_JNDSDQBD_ZHI": "添加你的閃電錢包地址",
          "TOU_XIANG": "頭像",
          "TIAN_JNDRZW_ZHI": "添加你的NIP-05認證網址",
          "WO": "我",
          "BAO_CUN": "保存",
          "QING_ZZLSRB_TI": "請在這裡輸入標題",
          "ZHANG_HAO": "賬號: ",
          "CU_ZDN_RONG": "促進使用或銷售非法或管制物質、煙草製品、彈藥和/或槍支的內容；",
          "ZAI_NDGRZLZTJJ_JIE": "在你的個人資料中添加簡介",
          "TONG_ZHI": "通知",
          "DI_ZHI": "地址",
          "YONG_H_MING": "用戶名",
          "JIA_RHM_DAN": "加入黑名單",
          "XING_Q_ER": "星期二",
          "NI_YSCZGZJQ_MA": "你要刪除這個中繼器嗎?",
          "SHU_YNZJDSJW_LUO": "屬於你自己的社交網絡",
          "LA_HEI": "封鎖用戶",
          "YI_Z_FA": "已轉發",
          "ZHANG_HMMS_YUE": "賬戶密碼私鑰",
          "ZE_REN": "責任",
          "TIAN": "天",
          "ZHUAN_ZHANG": "轉賬",
          "MING_ZBNW_KONG": "名字不能為空",
          "SHU_RZJQDD_ZHI": "輸入中繼器的地址",
          "TIAN_JNDM_ZI": "添加你的名字",
          "DENG_LU": "登錄",
          "WEN_ZHANG": "文章",
          "XING_Q_WU": "星期五",
          "NONE_ZZYHXKXY_NONE": "《最終用戶許可協議》",
          "ZHANG_HG_YUE_1": "賬戶ID公鑰",
          "YI_CSC_JIA": "移除收藏夾",
          "SAO_Y_S_MA": "掃一掃碼",
          "YI_TJZJ_QI": "已添加中繼器",
          "FU_ZTW_NONE": "複製帖子ID",
          "C_DELETE": "刪除",
          "TIAN_JFMTPCCW_NONE": "添加封面圖片尺寸為 2.35:1",
          "FA_Q_Q_LIAO": "發起群聊",
          "FEN_ZHONG": "分鐘",
          "FU_Z_C_GONG": "複製成功！",
          "SHOU_CANG": "收藏",
          "FA_BU": "發布",
          "FA_SONG": "發送",
          "BIAO_QIAN": "標籤",
          "KONG_HWXMCSRHQLTRSHWCN_REN": "* 恐嚇威脅、冒充、騷擾或欺凌他人，傷害未成年人;",
          "SHOU_D_NONE": "收到 500 SAT",
          "SHE_Z_B_ZHU": "設置備註",
          "BIAO_JWCWZ_NONE": "標記為長文章√",
          "WEI_G_H_GUO": "違規後果",
          "SHE_ZHI": "設置",
          "CHI_C_NONE": "尺寸 2.5:1",
          "XUAN_ZWZL_XING": "選擇文章類型",
          "GE_R_Z_LIAO": "個人資料",
          "TUI_W_X_QING": "Freerse詳情",
          "TI_SHI": "提示",
          "QIAN_BAO": "錢包",
          "ZUI_ZYHXKX_YI": "最終用戶許可協議 ",
          "DIAN_JI": "Zap",
          "SHAN_D_F_PIAO": "閃電發票",
          "SHAN_DQBD_ZHI": "閃電錢包地址",
          "CONG": "聰",
          "SAO_Y_SAO": "掃一掃",
          "JIN_ZNRHX_WEI": "禁止內容和行為 ",
          "YU_DBYGDFFN_RONG": "* 與賭博有關的非法內容;",
          "WO_D_S_CANG": "我的收藏",
          "XING_Q_SI": "星期四",
          "QU_XIAO": "取消",
          "BAN_B_NONE": "版本",
          "TIAN_JXDZJ_QI": "添加新的中繼器",
          "ZHONG_J_QI": "中繼器",
          "REN_MEN": "人們",
          "QUAN_Q_T_WEN": "全球",
          "ZHENG_C_F_BU": "正常發布",
          "COPY_DESC_10": "* 侵犯任何第三方權利的內容，包括版權、商標、隱私、宣傳或其他個人或專有權利，或者俱有欺騙性或欺詐性；",
          "HUI_FU_2": "回复:",
          "TIAN_JZYB_JING": "添加主頁背景",
          "TUI_W_LIAN": "Freerse鏈",
          "LIAN_X_REN": "聯繫人",
          "ZHI_FU": "支付",
          "TIE_ZJTBDWZX_SHI": "帖子將同步到文章顯示",
          "BAO_LIU_QUANLI":
              "我們保留隨時修改本 EULA 的權利，恕不另行通知。您在發布任何修改後的 EULA 後繼續使用該應用程序表明您接受修改後的 EULA 的條款。",
          "TONG_YBJ_XU": "同意並繼續",
          "XING_Q_TIAN": "星期日",
          "SOU_SUO": "搜索",
          "REN_ZHENG": "認證",
          "PRI_DESC":
              "私鑰是你的賬戶密碼，如果你丟失了你的私鑰，你將無法 訪問你的賬戶！私鑰沒有辦法找回，保存好你的私鑰，千萬不要透露給任何人。",
          "TIAN_JNDW_ZHAN": "添加你的網站",
          "TUI_WYH_FU": "回复",
          "WEN_ZDYX_XI": "文章訂閱消息",
          "COPY_DESC_12":
              "本最終用戶許可協議（“EULA”）是您與Freerse Inc. 之間關於使用移動應用程序 Freerse 的法律協議。通過安裝、訪問或使用我們的應用程序，您同意受本 EULA 的條款和條件的約束。如果您不同意本 EULA，則不得使用我們的應用程序。",
          "TIAN_XNDZHS_YUE": "填寫你的賬戶私鑰",
          "CHUANG_J_Z_HU": "創建賬戶",
          "QING_XTYX_YI": "請先同意協議",
          "TIAN_JDSC_JIA": "添加到收藏夾",
          "XING_Q_SAN": "星期三",
          "FU_ZYHG_YUE": "複製用戶ID公鑰",
          "WANG_ZHAN": "網站",
          "LA_HCY_HU": "拉黑此用戶",
          "SOU_S_NONE": "搜索Freeres",
          "XING_Q_YI": "星期一",
          "ZHANG_HG_YUE": "賬戶ID公鑰",
          "YI_YDBT_YI": "已閱讀並同意",
          "WO_YJBCLWDMMS_YUE": "我已經保存了我的密碼私鑰",
          "SHOU_F_KUAN": "收付款 ",
          "FU_Z_W_BEN": "複製文本",
          "GONG_YUE": "公鑰",
          "COPY_DESC_11":
              "我們的應用程序“按原樣”和“可用”提供，不提供任何明示或暗示的保證，包括但不限於對適銷性和特定用途適用性的暗示保證。我們不保證我們的應用程序不會中斷或沒有錯誤。在任何情況下，Freerse Inc. 均不對因使用或無法使用我們的應用程序而引起或與之相關的任何損害承擔責任，包括但不限於直接、間接、特殊、附帶或後果性損害。",
          "ZUO_TIAN": "昨天 ",
          "DAI_YQSXSDBLXYCHY_LUN": "* 帶有歧視性、煽動暴力、宣揚仇恨言論；",
          "NIN_TYBJYYJZDNRHXWBKDBX_YU": "您同意不將 Freerse 用於禁止的內容或行為，包括但不限於",
          "TIAN_J_F_WU": "添加服務",
          "SHUO_DSM_BA": "說點什麼吧...",
          "FEN_SI": "粉絲",
          "BIAN_JGRZ_LIAO": "編輯資料",
          "BANG_Z_Z_XIN": "幫助中心",
          "KAI_SHI": "開始",
          "YIN_HSQMFFBZSBLHHFFNRHX_DU": "* 淫穢、色情、冒犯、誹謗、中傷、暴力和/或非法內容或褻瀆；",
          "ZI_L_S_ZHI": "資料設置",
          "ZXQ_DI_QI":
              "第一排綠色的圓點是代表中繼器的網絡信號強弱，綠色是流暢，紅色是信號較弱。第二排的圖標中有Bitcoin的圖標的是付費中繼器.",
          "TIAN_S_RU": "添輸入",
          "ZHU_YBJ_TU": "主頁背景圖",
          "FU_ZYHGY_NONE": "複製用戶公鑰 Pubkey",
          "CONG_ZLKSXZ_WEN": "從這裡開始寫正文",
          "DIAN_ZAN": "點贊",
          "XIAO_SHI": "小時",
          "GUAN_Y_WO": "關於我",
          "ZHAO_PIAN": "照片",
          "BAO_CNDS_YUE": "保存你的私鑰",
          "BIAO_ZWCW_ZHANG": "標註為長文章",
          "MIAO": "秒",
          "TUI_WEN": "Freerse",
          "YU_LAN": "預覽",
          "QU_X_L_HEI": "取消拉黑",
          "RU_GNDCYRHYWQTGYWML_XI":
              "如果您對此 EULA 有任何疑問，請通過freerse8@gmail.com與我們聯繫。",
          "TIAN_JNDYH_MING": "添加你的用戶名",
          "JIE_S_T_KUAN": "接受條款",
          "BIAO_JWTW_NONE": "正常發布",
          "ZHI_D_L_TIAN": "置頂聊天",
          "JIE_SHOU": "接受",
          "GUAN_ZHU": "關注",
          "MING_ZI": "名字",
          "HUI_FU": "回复",
          "LISENCE_ACCEPT_DESC1":
              "使用我們的應用程序即表示您接受本EULA。如果您不同意本EULA，您不得使用我們的應用程序。",
          "QING_XQRYJBCMMS_YUE": "請先確認已經保存密碼私鑰",
          "XIAO_XI": "消息",
          "LIAN_X_F_SHI": "聯繫方式",
          "BA_TTJGP_YOU": "把他推薦給朋友",
          "TIAN_J_C_GONG": "添加成功！",
          "TIE_ZI": "Freerse",
          "ZHUAN_FA": "轉發",
          "FA_XIAN": "發現",
          "GUAN_Y_NONE": "關於Freerse",
          "XIN_D_P_YOU": "新的朋友",
          "GONG_YSNGZ_NI": "公鑰是你的賬戶ID，你可以復制發送給你的朋友，他可以通過公鑰搜索關注你。",
          "BIAN_G_NONE": "變更EULA",
          "NIP_AUTH": "NIP-05認證",
          "JUBAO": "舉報",
          "JUBAO_OK": "舉報成功",
          "JUBAO_LJ": "垃圾內容",
          "JUBAO_LT": "裸體或暴露的內容",
          "JUBAO_WG": "違規內容",
          "DELETE_ACCOUNT": "刪除賬戶",
          "DELETE_ACCOUNT_TIP": "你將刪除你的賬戶信息，你會失去你的賬戶所有信息，你確定要繼續刪除賬戶嗎？",
          "SHOW_MORE": "顯示更多",
          "ZAP_WALLET": "閃電錢包",
          "IMAGE": "图片",
          "ZAP_CONNECT_TIP":
              "貼上或輸入公鑰、Relay或Wallet Connect密鑰。僅支援支援Nostr Wallet Connect協議的錢包。",
          "PASTE_OR_ENTER_HERE": "請在此處貼上或輸入",
          "PASTE": "粘貼",
          "CLEAR": "清除",
          "CONNECT_WALLET": "連接錢包",
          "SCAN_QR_CODE": "掃描QR碼",
          "CONNECT_OTHER_WALLETS": "連接其他錢包",
          "OTHER_AMOUNT": "其他金額",
          "PLEASE_INPUT_AMOUNT": "請輸入數量",
          "MESSAGE": "留言",
          "PLEASE_INPUT_MESSAGE": "請輸入留言",
          "CONFIRM": "確定",
          "DEFAULT_ZAP_AMOUNT_IN_SATS": "預設Zap金額，以sat為單位。",
          "ZAP_AMOUNT_TIP":
              "1個比特幣=100,000,000 sats，點擊Zap發送預設金額，長按Zap按鈕可以發送自定義金額。",
          "SET_CUSTOM_ZAP_AMOUNT": "設置自定義Zap金額",
          "RESTORE_DEFAULT_SETTINGS": "恢復默認設置",
          "ZAP_AMOUNT_SETTINGS": "Zap金額設定",
          "BITCOIN_LIGHTNING_WALLET": "比特幣閃電錢包",
          "ZAP_RECEIVE_SEND_TIP": "發送和接受Zap，請連接一個比特幣閃電錢包。",
          "ZAP_DES": "Zap是用比特幣獎勵您喜歡的帖子的一種方式。",
          "ALBY_BITCOIN_LIGHTNING_WALLET_IS_CONNECTED": "已連接Alby比特幣閃電錢包。",
          "BITCOIN_LIGHTNING_WALLET_IS_CONNECTED": "已連接比特幣閃電錢包。",
          "DISCONNECT_WALLET": "斷開錢包",
          "CONNECT_ALBY_WALLET": "連接Alby錢包",
          "DISCONNECT_TIP": "斷開錢包連線將無法發送 zap，此錢包地址仍可接收 zap。如需修改錢包地址，請在個人資料中修改。",
          "ZAP_SENDING": "Zap發送中",
          "NO_WALLET_WAS_FOUND": "没有找到到錢包。",
          "THIS_ACCOUNT_DOES_NOT_HAVE_A_WALLET_ADDRESS_SET": "此帳戶沒有設定錢包地址。",
          "QUOTE": "引用",
          "DONATE": "捐赠",
          "DONATE_DES1": "支持 Freerse",
          "DONATE_DES2": "幫助建造去中心化的社交網路。",
          "RETWEETED": "轉發了",
          "ZAPED": "打闪了",
          "REACTED": "点赞了",
          "AND": "和",
          "OTHERS": "其他人",
          "YOUR_FREERSE": "你的freerse",
          "YOU": "你",
          "H_Y_S_Q_X_X": "好友申請消息",
          "SAVE_IMAGE_SUCCESS": "已儲存至相簿",
          "LOADING": "載入中",
          "FAILED_TO_SEND": "發送失敗",
          "THANKS_DONATE": "感謝捐贈",
          "ZAP_FAIL": "zap失敗",
          "DONATE1_NAME": "Freerse 捐贈 1",
          "DONATE2_NAME": "Freerse 捐贈 2",
          "DONATE3_NAME": "Freerse 捐贈 3",
          "DONATE4_NAME": "Freerse 捐贈 4",
          "COPY": "复制",
        },
        'en_US': {
          "OUT_APP_TIP": "Press again to exit the app",
          "SET_ACCOUNT": "Account",
          "GUAN_ZHU": "Follow",
          "QU_SHI": "Trend 24h",
          "MENU_THEME": "Appearance",
          "MENU_LOCAL": "Multi-language",
          "SET_THEME": "Set theme",
          "THEME_AUTO": "Follow the system",
          "THEME_LIGHT": "Light color",
          "THEME_DARK": "Dark",
          "SET_LOCAL": "Set language",
          "EN_US": "English",
          "ZH_CN": "Simplified Chinese",
          "ZH_TW": "Traditional Chinese",
          "JA_JP": "Japanese",
          "TH_TH": "Thai",
          "FR_CH": "French",
          "PT_BR": "Portuguese",
          "TIAO": "Article",
          "YONG_HU": "User",
          "YI_QJRZYY_ZHOU": "Enter the free universe together",
          "XING_Q_LIU": "Saturday",
          "QING_SRHYB_ZHU": "Please enter friend notes",
          "TUI_C_D_LU": "Logout",
          "QU_X_G_ZHU": "Unfollow",
          "ZHONG_XU_QI_DESC":
              "A relay is like a server, used to store and retrieve data. The Freerse client is created on Nostr. Nostr is decentralized, and there are many relay that provide data storage and retrieval services. You add How many relay you have, your data will be transferred and backed up on as many relay, you can add relay you like.",
          "TIAN_JIA": "Add",
          "COPY_DESC":
              "Any violation of this EULA, including prohibited content and conduct above, may result in termination of your access to our application.",
          "CHUANG_JNDZ_HU": "Create your account",
          "SI_YUE": "Private Key",
          "TIAN_JNDSDQBD_ZHI": "Add your lightning wallet address",
          "TOU_XIANG": "Avatar",
          "TIAN_JNDRZW_ZHI": "Add your NIP-05 authentication URL",
          "WO": "Me",
          "BAO_CUN": "Save",
          "QING_ZZLSRB_TI": "Please enter a title here",
          "ZHANG_HAO": "Account: ",
          "CU_ZDN_RONG":
              "Content that promotes the use or sale of illegal or controlled substances, tobacco products, ammunition, and/or firearms;",
          "ZAI_NDGRZLZTJJ_JIE": "Add an introduction to your profile",
          "TONG_ZHI": "Notification",
          "DI_ZHI": "Address",
          "YONG_H_MING": "Username",
          "JIA_RHM_DAN": "Mute user",
          "XING_Q_ER": "Tuesday",
          "NI_YSCZGZJQ_MA": "Do you want to delete this relay?",
          "SHU_YNZJDSJW_LUO": "Your own social network",
          "LA_HEI": "Block User",
          "YI_Z_FA": "Forwarded",
          "ZHANG_HMMS_YUE": "Password Private Key",
          "ZE_REN": "Responsibility",
          "TIAN": "day",
          "ZHUAN_ZHANG": "Transfer",
          "MING_ZBNW_KONG": "Name cannot be empty",
          "SHU_RZJQDD_ZHI": "Enter the address of the relay",
          "TIAN_JNDM_ZI": "Add your name",
          "DENG_LU": "Login",
          "WEN_ZHANG": "Article",
          "XING_Q_WU": "Friday",
          "NONE_ZZYHXKXY_NONE": "End User License Agreement",
          "ZHANG_HG_YUE_1": "Account ID public key",
          "YI_CSC_JIA": "Remove favorite",
          "SAO_Y_S_MA": "Scan QR code",
          "YI_TJZJ_QI": "Relay added",
          "FU_ZTW_NONE": "Copy Post ID",
          "C_DELETE": "Delete",
          "TIAN_JFMTPCCW_NONE": "Add a cover image with a size of 2.35:1",
          "FA_Q_Q_LIAO": "Start a group chat",
          "FEN_ZHONG": "Minutes",
          "FU_Z_C_GONG": "Copy successful!",
          "SHOU_CANG": "Favorites",
          "FA_BU": "Publish",
          "FA_SONG": "Send",
          "BIAO_QIAN": "Hashtags",
          "KONG_HWXMCSRHQLTRSHWCN_REN":
              "* Intimidating, threatening, impersonating, harassing or bullying others, harming minors;",
          "SHOU_D_NONE": "500 SAT received",
          "SHE_Z_B_ZHU": "Set Remarks",
          "BIAO_JWCWZ_NONE": "long article√",
          "WEI_G_H_GUO": "Consequences of Violation",
          "SHE_ZHI": "Settings",
          "CHI_C_NONE": "Size 2.5:1",
          "XUAN_ZWZL_XING": "Select Article Type",
          "GE_R_Z_LIAO": "Profile",
          "TUI_W_X_QING": "Freerse Details",
          "TI_SHI": "Notice",
          "QIAN_BAO": "Wallet",
          "ZUI_ZYHXKX_YI": "End User License Agreement",
          "DIAN_JI": "Zap",
          "SHAN_D_F_PIAO": "Lightning Invoice",
          "SHAN_DQBD_ZHI": "Lightning wallet address",
          "CONG": "Cong",
          "SAO_Y_SAO": "Scan",
          "JIN_ZNRHX_WEI": "Prohibited content and behavior",
          "YU_DBYGDFFN_RONG": "* Illegal content related to gambling;",
          "WO_D_S_CANG": "My Favorites",
          "XING_Q_SI": "Thursday",
          "QU_XIAO": "Cancel",
          "BAN_B_NONE": "Version ",
          "TIAN_JXDZJ_QI": "Add new relay",
          "ZHONG_J_QI": "Relay",
          "REN_MEN": "People",
          "QUAN_Q_T_WEN": "Global",
          "ZHENG_C_F_BU": "Publish normally",
          "COPY_DESC_10":
              "* Content that violates the rights of any third party, including copyright, trademark, privacy, publicity, or other personal or proprietary rights, or that is deceptive or fraudulent;",
          "HUI_FU_2": "Reply:",
          "TIAN_JZYB_JING": "Add home page background",
          "TUI_W_LIAN": "Freerse Chain",
          "LIAN_X_REN": "Contact",
          "ZHI_FU": "Payment",
          "TIE_ZJTBDWZX_SHI":
              "The post will be synchronized to the article display",
          "BAO_LIU_QUANLI":
              "We reserve the right to modify this EULA at any time without notice. Your continued use of the app after posting of any modified EULA indicates your acceptance of the terms of the modified EULA.",
          "TONG_YBJ_XU": "Agree and continue",
          "XING_Q_TIAN": "Sunday",
          "SOU_SUO": "Search",
          "REN_ZHENG": "Authentication",
          "PRI_DESC":
              "The private key is your account password. If you lose your private key, you will not be able to access your account! There is no way to retrieve the private key. Keep your private key safe and do not disclose it to anyone. people.",
          "TIAN_JNDW_ZHAN": "Add your website",
          "TUI_WYH_FU": "Reply",
          "WEN_ZDYX_XI": "Article subscription news",
          "COPY_DESC_12":
              "This End User License Agreement ('EULA') is a legal agreement between you and Freerse Inc. regarding the use of the mobile application Freerse. By installing, accessing or using our application, you agree to be bound by this EULA Terms and Conditions. If you do not agree to this EULA, you may not use our App.",
          "TIAN_XNDZHS_YUE": "Fill in your account private key",
          "CHUANG_J_Z_HU": "Create",
          "QING_XTYX_YI": "Please agree to the agreement first",
          "TIAN_JDSC_JIA": "Add to Favorites",
          "XING_Q_SAN": "Wednesday",
          "FU_ZYHG_YUE": "Copy User ID Public Key",
          "WANG_ZHAN": "Website",
          "LA_HCY_HU": "Mute user",
          "SOU_S_NONE": "Search Freeres",
          "XING_Q_YI": "Monday",
          "ZHANG_HG_YUE": "Account ID Public Key",
          "YI_YDBT_YI": "Read and Agree",
          "WO_YJBCLWDMMS_YUE": "I have saved my password private key",
          "SHOU_F_KUAN": "Receipt and Payment",
          "FU_Z_W_BEN": "Copy Text",
          "GONG_YUE": "Public Key",
          "COPY_DESC_11":
              "Our app is provided as is and as available without warranty of any kind, either expressed or implied, including but not limited to the implied warranties of merchantability and fitness for a particular purpose. We make no warranty that our app The program will be uninterrupted or error-free.Under no circumstances will Freerse Inc. be liable for any damages of any kind whatsoever, including, but not limited to, direct, indirect, special, incidental, or consequential damages.",
          "ZUO_TIAN": "Yesterday",
          "DAI_YQSXSDBLXYCHY_LUN":
              "* is discriminatory, incites violence, promotes hate speech;",
          "NIN_TYBJYYJZDNRHXWBKDBX_YU":
              "You agree not to use Freerse for prohibited content or conduct, including but not limited to",
          "TIAN_J_F_WU": "Add Service",
          "SHUO_DSM_BA": "Say something...",
          "FEN_SI": "Fan",
          "BIAN_JGRZ_LIAO": "Edit Profile",
          "BANG_Z_Z_XIN": "Help Center",
          "KAI_SHI": "Start",
          "YIN_HSQMFFBZSBLHHFFNRHX_DU":
              "* Obscene, pornographic, offensive, defamatory, libelous, violent and/or illegal or profane;",
          "ZI_L_S_ZHI": "Profile Settings",
          "ZXQ_DI_QI":
              "The green dots in the first row represent the strength of the network signal of the relay, the green is smooth, and the red is weak signal. The second row of icons with the Bitcoin icon is a paid relay. ",
          "TIAN_S_RU": "Tian input",
          "ZHU_YBJ_TU": "Home page background image",
          "FU_ZYHGY_NONE": "Copy user public key Pubkey",
          "CONG_ZLKSXZ_WEN": "Write text from here",
          "DIAN_ZAN": "Like",
          "XIAO_SHI": "Hour",
          "GUAN_Y_WO": "About Me",
          "ZHAO_PIAN": "Photo",
          "BAO_CNDS_YUE": "Save your private key",
          "BIAO_ZWCW_ZHANG": "long article",
          "MIAO": "seconds",
          "TUI_WEN": "Freerse",
          "YU_LAN": "Preview",
          "QU_X_L_HEI": "Cancel blocking",
          "RU_GNDCYRHYWQTGYWML_XI":
              "If you have any questions about this EULA, please contact us at freerse8@gmail.com.",
          "TIAN_JNDYH_MING": "Add your username",
          "JIE_S_T_KUAN": "Accept Terms",
          "BIAO_JWTW_NONE": "Publish normally",
          "ZHI_D_L_TIAN": "Top chat",
          "JIE_SHOU": "Accept",
          "GUAN_ZHU": "Follow",
          "MING_ZI": "Name",
          "HUI_FU": "Reply",
          "LISENCE_ACCEPT_DESC1":
              "By using our application you accept this EULA. If you do not agree to this EULA, you may not use our application.",
          "QING_XQRYJBCMMS_YUE":
              "Please confirm that the password private key has been saved first",
          "XIAO_XI": "Message",
          "LIAN_X_F_SHI": "Contact Information",
          "BA_TTJGP_YOU": "Recommend him to a friend",
          "TIAN_J_C_GONG": "Added successfully!",
          "TIE_ZI": "Freerse",
          "ZHUAN_FA": "Forward",
          "FA_XIAN": "Discovery",
          "GUAN_Y_NONE": "About Freerse",
          "XIN_D_P_YOU": "New friend",
          "GONG_YSNGZ_NI":
              "The public key is your account ID, you can copy and send it to your friends, and he can search and follow you through the public key.",
          "BIAN_G_NONE": "Change EULA",
          "NIP_AUTH": "NIP-05 Authentication",
          "JUBAO": "Report",
          "JUBAO_OK": "Report successful",
          "JUBAO_LJ": "Jubao",
          "JUBAO_LT": "Nude or revealing content",
          "JUBAO_WG": "Violation Content",
          "DELETE_ACCOUNT": "Delete Account",
          "DELETE_ACCOUNT_TIP":
              "You will delete your account information, you will lose all your account information, are you sure you want to continue to delete the account?",
          "SHOW_MORE": "Show More",
          "ZAP_WALLET": "Lightning Wallet",
          "IMAGE": "Image",
          "ZAP_CONNECT_TIP":
              "Paste or enter public key, relay, or Wallet Connect Secret. Only supports wallets that support the Nostr Wallet Connect protocol.",
          "PASTE_OR_ENTER_HERE": "Paste or enter here",
          "PASTE": "Paste",
          "CLEAR": "Clear",
          "CONNECT_WALLET": "Connect Wallet",
          "SCAN_QR_CODE": "Scan QR code",
          "CONNECT_OTHER_WALLETS": "Connect Other Wallets",
          "OTHER_AMOUNT": "Other amount",
          "PLEASE_INPUT_AMOUNT": "Please input amount",
          "MESSAGE": "Message",
          "PLEASE_INPUT_MESSAGE": "Please input message",
          "CONFIRM": "Confirm",
          "DEFAULT_ZAP_AMOUNT_IN_SATS": "Default Zap amount, in sats.",
          "ZAP_AMOUNT_TIP":
              "1 Bitcoin = 100,000,000 sats, tap Zap to send the default amount, press and hold the Zap button to send a custom amount.",
          "SET_CUSTOM_ZAP_AMOUNT": "Set custom Zap amount",
          "RESTORE_DEFAULT_SETTINGS": "Restore default settings",
          "ZAP_AMOUNT_SETTINGS": "Zap Amount Settings",
          "BITCOIN_LIGHTNING_WALLET": "Bitcoin Lightning Wallet",
          "ZAP_RECEIVE_SEND_TIP":
              "To send and receive Zap, you must connect a Bitcoin Lightning Wallet.",
          "ZAP_DES": "Zap is a way to tip your favorite posts with Bitcoin.",
          "ALBY_BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "Alby Bitcoin Lightning Wallet is connected.",
          "BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "Bitcoin Lightning Wallet is connected.",
          "DISCONNECT_WALLET": "Disconnect Wallet",
          "CONNECT_ALBY_WALLET": "Connect Alby Wallet",
          "DISCONNECT_TIP":
              "Disconnecting your wallet will prevent you from sending zaps. This wallet address can still receive zaps. If you need to change your wallet address, please update it in your profile.",
          "ZAP_SENDING": "Zap sending",
          "NO_WALLET_WAS_FOUND": "No wallet was found.",
          "THIS_ACCOUNT_DOES_NOT_HAVE_A_WALLET_ADDRESS_SET":
              "This account does not have a wallet address set.",
          "QUOTE": "Quote",
          "DONATE": "Donate",
          "DONATE_DES1": "Support Freerse",
          "DONATE_DES2": "Help build a decentralized social network.",
          "RETWEETED": "retweeted",
          "ZAPED": "zaped",
          "REACTED": "reacted",
          "AND": "and",
          "OTHERS": "others",
          "YOUR_FREERSE": "your freerse",
          "YOU": "you",
          "H_Y_S_Q_X_X": "Friend request message",
          "SAVE_IMAGE_SUCCESS": "Saved to album successfully",
          "LOADING": "Loading",
          "FAILED_TO_SEND": "Failed to send",
          "THANKS_DONATE": "Thanks for donating",
          "ZAP_FAIL": "Zap Fail",
          "DONATE1_NAME": "Freerse Donation 1",
          "DONATE2_NAME": "Freerse Donation 2",
          "DONATE3_NAME": "Freerse Donation 3",
          "DONATE4_NAME": "Freerse Donation 4",
        },
        'ja_JP': {
          "OUT_APP_TIP": "もう一度押すとアプリを終了します",
          "SET_ACCOUNT": "アカウント",
          "GUAN_ZHU": "フォロー",
          "QU_SHI": "トレンド 24h",
          "MENU_THEME": "外観",
          "MENU_LOCAL": "多言語",
          "SET_THEME": "テーマを設定",
          "THEME_AUTO": "システムに従います",
          "THEME_LIGHT": "明るい色",
          "THEME_DARK": "ダーク",
          "SET_LOCAL": "言語を設定",
          "EN_US": "英語",
          "ZH_CN": "簡体字中国語",
          "ZH_TW": "繁体字中国語",
          "JA_JP": "日本語",
          "TH_TH": "タイ語",
          "FR_CH": "フランス語",
          "PT_BR": "ポルトガル語",
          "TIAO": "記事",
          "YONG_HU": "ユーザー",
          "YI_QJRZYY_ZHOU": "一緒に自由な世界に入りましょう",
          "XING_Q_LIU": "土曜日",
          "QING_SRHYB_ZHU": "友達のメモを入力してください",
          "TUI_C_D_LU": "ログアウト",
          "QU_X_G_ZHU": "フォローを解除",
          "ZHONG_XU_QI_DESC":
              "リピーターはサーバーのようなもので、データの保存と取得に使用されます。Freerse クライアントは Nostr 上に作成されます。Nostr は分散型であり、データの保存と取得サービスを提供するリピーターが多数あります。リピーターの数を追加します。データはリピーターの数だけ転送およびバックアップされるので、好きなリピーターを追加できます。",
          "TIAN_JIA": "追加",
          "COPY_DESC":
              "禁止されたコンテンツや上記の行為を含め、この EULA に違反すると、アプリケーションへのアクセスが停止される場合があります。",
          "CHUANG_JNDZ_HU": "アカウントを作成してください",
          "SI_YUE": "秘密鍵",
          "TIAN_JNDSDQBD_ZHI": "ライトニング ウォレット アドレスを追加します",
          "TOU_XIANG": "アバター",
          "TIAN_JNDRZW_ZHI": "NIP-05 認証 URL を追加します",
          "WO": "私",
          "BAO_CUN": "保存",
          "QING_ZZLSRB_TI": "ここにタイトルを入力してください",
          "ZHANG_HAO": "アカウント: ",
          "CU_ZDN_RONG": "違法または規制物質、タバコ製品、弾薬、および/または銃器の使用または販売を促進するコンテンツ;",
          "ZAI_NDGRZLZTJJ_JIE": "プロフィールに紹介文を追加します",
          "TONG_ZHI": "通知",
          "DI_ZHI": "住所",
          "YONG_H_MING": "ユーザー名",
          "JIA_RHM_DAN": "ブラックリストに追加",
          "XING_Q_ER": "火曜日",
          "NI_YSCZGZJQ_MA": "このリピーターを削除しますか?",
          "SHU_YNZJDSJW_LUO": "独自のソーシャル ネットワーク",
          "LA_HEI": "ユーザをブロックする",
          "YI_Z_FA": "転送されました",
          "ZHANG_HMMS_YUE": "アカウントのパスワード秘密キー",
          "ZE_REN": "責任",
          "TIAN": "日",
          "ZHUAN_ZHANG": "転送",
          "MING_ZBNW_KONG": "名前を空にすることはできません",
          "SHU_RZJQDD_ZHI": "リピーターのアドレスを入力してください",
          "TIAN_JNDM_ZI": "名前を追加してください",
          "DENG_LU": "ログイン",
          "WEN_ZHANG": "記事",
          "XING_Q_WU": "金曜日",
          "NONE_ZZYHXKXY_NONE": "エンドユーザー使用許諾契約",
          "ZHANG_HG_YUE_1": "アカウント ID 公開キー",
          "YI_CSC_JIA": "お気に入りを削除",
          "SAO_Y_S_MA": "QR コードをスキャン",
          "YI_TJZJ_QI": "リピーターを追加しました",
          "FU_ZTW_NONE": "投稿 ID をコピー",
          "C_DELETE": "削除",
          "TIAN_JFMTPCW_NONE": "サイズ 2.35:1 のカバー画像を追加します",
          "FA_Q_Q_LIAO": "グループ チャットを開始します",
          "FEN_ZHONG": "分",
          "FU_Z_C_GONG": "コピー成功!",
          "SHOU_CANG": "お気に入り",
          "FA_BU": "公開",
          "FA_SONG": "送信",
          "BIAO_QIAN": "ラベル",
          "KONG_HWXMCSRHQLTRSHWCN_REN": "* 他者への脅迫、脅迫、なりすまし、嫌がらせやいじめ、未成年者への危害;",
          "SHOU_D_NONE": "500 SAT を受け取りました",
          "SHE_Z_B_ZHU": "備考を設定",
          "BIAO_JWCWZ_NONE": "長い記事としてマーク√",
          "WEI_G_H_GUO": "違反の結果",
          "SHE_ZHI": "設定",
          "CHI_C_NONE": "サイズ 2.5:1",
          "XUAN_ZWZL_XING": "記事の種類を選択",
          "GE_R_Z_LIAO": "プロフィール",
          "TUI_W_X_QING": "Freerse詳細",
          "TI_SHI": "ヒント",
          "QIAN_BAO": "ウォレット",
          "ZUI_ZYHXKX_YI": "エンドユーザー使用許諾契約",
          "DIAN_JI": "Zap",
          "SHAN_D_F_PIAO": "ライトニング請求書",
          "SHAN_DQBD_ZHI": "ライトニングウォレットアドレス",
          "CONG": "コング",
          "SAO_Y_SAO": "スキャン",
          "JIN_ZNRHX_WEI": "禁止されたコンテンツと動作",
          "YU_DYGDFFN_RONG": "* ギャンブルに関連する違法なコンテンツ;",
          "WO_D_S_CANG": "お気に入り",
          "XING_Q_SI": "木曜日",
          "QU_XIAO": "キャンセル",
          "BAN_B_NONE": "バージョン ",
          "TIAN_JXDZJ_QI": "新しいリピーターを追加",
          "ZHONG_J_QI": "リピーター",
          "REN_MEN": "人",
          "QUAN_Q_T_WEN": "グローバル",
          "ZHENG_C_F_BU": "通常通り公開",
          "COPY_DESC_10":
              "* 著作権、商標、プライバシー、パブリシティ、その他の個人的権利や所有権を含む第三者の権利を侵害するコンテンツ、または欺瞞的または詐欺的なコンテンツ;",
          "HUI_FU_2": "返信:",
          "TIAN_JZYB_JING": "ホームページの背景を追加",
          "TUI_W_LIAN": "Freerseーン",
          "LIAN_X_REN": "連絡先",
          "ZHI_FU": "支払い",
          "TIE_ZJTBDWZX_SHI": "投稿は記事表示と同期されます",
          "BAO_LIU_QUANLI":
              "当社は、いつでも予告なくこの EULA を変更する権利を留保します。変更された EULA の投稿後にアプリを継続して使用することは、変更された EULA の条項に同意したことを示します。",
          "TONG_YBJ_XU": "同意して続行",
          "XING_Q_TIAN": "日曜日",
          "SOU_SUO": "検索",
          "REN_ZHENG": "認証",
          "PRI_DESC":
              "秘密キーはアカウントのパスワードです。秘密キーを紛失すると、アカウントにアクセスできなくなります。秘密キーを取得する方法はありません。秘密キーは安全に保管し、公開しないでください。誰にでも、人々にでも。」",
          "TIAN_JNDW_ZHAN": "ウェブサイトを追加",
          "TUI_WYH_FU": "返信",
          "WEN_ZDYX_XI": "記事購読ニュース",
          "COPY_DESC_12":
              "このエンド ユーザー ライセンス契約 (「EULA」) は、モバイル アプリケーション Freerse の使用に関するお客様と Freerse Inc. との間の法的契約です。当社のアプリケーションをインストール、アクセス、または使用することにより、お客様はこれに拘束されることに同意したことになります。 EULA 利用規約。この EULA に同意しない場合は、当社のアプリを使用することはできません。",
          "TIAN_XNDZHS_YUE": "アカウントの秘密キーを入力してください",
          "CHUANG_J_Z_HU": "作成",
          "QING_XTYX_YI": "まず契約書に同意してください",
          "TIAN_JDSC_JIA": "お気に入りに追加",
          "XING_Q_SAN": "水曜日",
          "FU_ZYHG_YUE": "ユーザー ID 公開キーをコピー",
          "WANG_ZHAN": "ウェブサイト",
          "LA_HCY_HU": "このユーザーをブロックします",
          "SOU_S_NONE": "フリーレスを検索",
          "XING_Q_YI": "月曜日",
          "ZHANG_HG_YUE": "アカウント ID 公開キー",
          "YI_YDBT_YI": "読んで同意します",
          "WO_YJBCLWDMMS_YUE": "パスワードの秘密キーを保存しました",
          "SHOU_F_KUAN": "受け取りと支払い",
          "FU_Z_W_BEN": "テキストをコピー",
          "GONG_YUE": "公開鍵",
          "COPY_DESC_11":
              "当社のアプリは「現状のまま」および「利用可能な状態で」提供されており、商品性や特定の目的への適合性の暗黙の保証を含むがこれに限定されない、明示的か黙示的かを問わず、いかなる種類の保証もありません。当社のアプリは、プログラムが中断されず、エラーも発生しません。いかなる状況においても、Freerse Inc. は、直接的、間接的、特別、偶発的、結果的損害を含むがこれらに限定されない、いかなる種類の損害に対しても責任を負いません。",
          "ZUO_TIAN": "昨日",
          "DAI_YQSXSDBLXYCHY_LUN": "* は差別的であり、暴力を扇動し、ヘイトスピーチを促進します;",
          "NIN_TYBJYYJZDNRHXWBKDBX_YU":
              "禁止されたコンテンツまたは行為 (これに限定されない) に Freerse を使用しないことに同意します",
          "TIAN_J_F_WU": "サービスを追加",
          "SHUO_DSM_BA": "何か言ってください...",
          "FEN_SI": "ファン",
          "BIAN_JGRZ_LIAO": "プロフィールを編集",
          "BANG_Z_Z_XIN": "ヘルプセンター",
          "KAI_SHI": "開始",
          "YIN_HSQMFFBZSBLHHFFNRHX_DU":
              "* わいせつ、ポルノ、攻撃的、名誉毀損、名誉毀損、暴力的および/または違法または冒涜的;",
          "ZI_L_S_ZHI": "プロファイル設定",
          "ZXQ_DI_QI":
              "最初の行の緑の点はリピーターのネットワーク信号の強度を表し、緑は滑らかで、赤は弱い信号を表します。ビットコインアイコンの付いたアイコンの2行目は有料リピーターです。",
          "TIAN_S_RU": "ティアン入力",
          "ZHU_YBJ_TU": "ホームページの背景画像",
          "FU_ZYHGY_NONE": "ユーザーの公開鍵 Pubkey をコピー",
          "CONG_ZLKSXZ_WEN": "ここからテキストを書き込みます",
          "DIAN_ZAN": "いいね",
          "XIAO_SHI": "時",
          "GUAN_Y_WO": "私のこと",
          "ZHAO_PIAN": "写真",
          "BAO_CNDS_YUE": "秘密キーを保存します",
          "BIAO_ZWCW_ZHANG": "長い記事としてマーク",
          "MIAO": "秒",
          "TUI_WEN": "フリーザー",
          "YU_LAN": "プレビュー",
          "QU_X_L_HEI": "ブロックをキャンセル",
          "RU_GNDCYRHYWQTGYWML_XI":
              "この EULA についてご質問がある場合は、freerse8@gmail.com までご連絡ください。",
          "TIAN_JNDYH_MING": "ユーザー名を追加",
          "JIE_S_T_KUAN": "規約に同意します",
          "BIAO_JWTW_NONE": "通常通り公開",
          "ZHI_D_L_TIAN": "トップチャット",
          "JIE_SHOU": "受け入れる",
          "GUAN_ZHU": "フォロー",
          "MING_ZI": "名前",
          "HUI_FU": "返信",
          "LISENCE_ACCEPT_DESC1":
              "当社のアプリケーションを使用することにより、この EULA に同意したことになります。この EULA に同意しない場合は、当社のアプリケーションを使用することはできません。",
          "QING_XQRYJBCMMS_YUE": "最初にパスワード秘密キーが保存されていることを確認してください",
          "XIAO_XI": "メッセージ",
          "LIAN_X_F_SHI": "連絡先情報",
          "BA_TTJGP_YOU": "彼を友達に勧めます",
          "TIAN_J_C_GONG": "正常に追加されました!",
          "TIE_ZI": "フリーザー",
          "ZHUAN_FA": "進む",
          "FA_XIAN": "発見",
          "GUAN_Y_NONE": "フリー Freerse",
          "XIN_D_P_YOU": "新しい友達",
          "GONG_YSNGZ_NI":
              "公開キーはあなたのアカウント ID です。これをコピーして友人に送信すると、友人は公開キーを使用してあなたを検索し、フォローすることができます。",
          "BIAN_G_NONE": "EULA を変更",
          "NIP_AUTH": "NIP-05 認証",
          "JUBAO": "報告",
          "JUBAO_OK": "レポートは成功しました",
          "JUBAO_LJ": "ジュバオ",
          "JUBAO_LT": "ヌードまたは露出度の高いコンテンツ",
          "JUBAO_WG": "違反内容",
          "DELETE_ACCOUNT": "アカウントを削除",
          "DELETE_ACCOUNT_TIP":
              "アカウント情報を削除すると、すべてのアカウント情報が失われます。アカウントの削除を続行してもよろしいですか?",
          "SHOW_MORE": "もっと見せる",
          "ZAP_WALLET": "ライトニングウォレット",
          "IMAGE": "写真",
          "ZAP_CONNECT_TIP":
              "公開キー、Relay、およびWallet Connect Secretを貼り付けるか入力します。Nostr Wallet Connect プロトコルに適合したウォレットのみがサポートされます。",
          "PASTE_OR_ENTER_HERE": "ここに貼り付けるか入力します",
          "PASTE": "貼り付け",
          "CLEAR": "クリア",
          "CONNECT_WALLET": "ウォレットを接続する",
          "SCAN_QR_CODE": "QRコードをスキャンする",
          "CONNECT_OTHER_WALLETS": "他のウォレットを接続する",
          "OTHER_AMOUNT": "その他の金額",
          "PLEASE_INPUT_AMOUNT": "金額を入力してください",
          "MESSAGE": "メッセージ",
          "PLEASE_INPUT_MESSAGE": "メッセージを入力してください",
          "CONFIRM": "確認する",
          "DEFAULT_ZAP_AMOUNT_IN_SATS": "デフォルトのZap金額、sat単位。",
          "ZAP_AMOUNT_TIP":
              "1ビットコイン = 100,000,000 sats、Zapをタップするとデフォルトの金額を送信し、Zapボタンを長押しするとカスタム金額を送信できます。",
          "SET_CUSTOM_ZAP_AMOUNT": "カスタムZap金額を設定",
          "RESTORE_DEFAULT_SETTINGS": "デフォルトの設定を復元",
          "ZAP_AMOUNT_SETTINGS": "Zap金額設定",
          "BITCOIN_LIGHTNING_WALLET": "ビットコインライトニングウォレット",
          "ZAP_RECEIVE_SEND_TIP": "Zapを送受信するには、ビットコインライトニングウォレットを接続する必要があります。",
          "ZAP_DES": "Zapは、ビットコインを使ってお気に入りの投稿にチップを送る方法です。",
          "ALBY_BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "Albyビットコインライトニングウォレットが接続されています。",
          "BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "ビットコインライトニングウォレットが接続されています。",
          "DISCONNECT_WALLET": "ウォレットを切断する",
          "CONNECT_ALBY_WALLET": "Albyウォレットを接続する",
          "DISCONNECT_TIP":
              "ウォレットを切断すると、zap を送信できなくなります。このウォレット アドレスは引き続き zap を受信できます。ウォレット アドレスを変更する必要がある場合は、プロフィールで更新してください。",
          "ZAP_SENDING": "Zap 送信",
          "NO_WALLET_WAS_FOUND": "ウォレットが見つかりませんでした。",
          "THIS_ACCOUNT_DOES_NOT_HAVE_A_WALLET_ADDRESS_SET":
              "このアカウントにはウォレット アドレスが設定されていません。",
          "QUOTE": "引用",
          "DONATE": "寄付する",
          "DONATE_DES1": "Freerse を支援して",
          "DONATE_DES2": "分散型ソーシャルネットワークを構築する。",
          "RETWEETED": "リツイートした",
          "ZAPED": "zaped",
          "REACTED": "反応した",
          "AND": "そして",
          "OTHERS": "他の人",
          "YOUR_FREERSE": "あなたのfreerse",
          "YOU": "あなた",
          "H_Y_S_Q_X_X": "友達申請メッセージ",
          "SAVE_IMAGE_SUCCESS": "アルバムに保存されました",
          "LOADING": "読み込み中",
          "FAILED_TO_SEND": "送信に失敗しました",
          "THANKS_DONATE": "寄付していただきありがとうございます",
          "ZAP_FAIL": "Zap失敗",
          "DONATE1_NAME": "Freerse 寄付 1",
          "DONATE2_NAME": "Freerse 寄付 2",
          "DONATE3_NAME": "Freerse 寄付 3",
          "DONATE4_NAME": "Freerse 寄付 4",
        },
        'th_TH': {
          "OUT_APP_TIP": "กดอีกครั้งเพื่อออกจากแอป",
          "SET_ACCOUNT": "บัญชี",
          "GUAN_ZHU": "ติดตาม",
          "QU_SHI": "เทรนด์ 24h",
          "MENU_THEME": "รูปลักษณ์",
          "MENU_LOCAL": "หลายภาษา",
          "SET_THEME": "ตั้งค่าธีม",
          "THEME_AUTO": "ติดตามระบบ",
          "THEME_LIGHT": "สีอ่อน",
          "THEME_DARK": "มืด",
          "SET_LOCAL": "ตั้งค่าภาษา",
          "EN_US": "อังกฤษ",
          "ZH_CN": "จีนตัวย่อ",
          "ZH_TW": "ภาษาจีนตัวเต็ม",
          "JA_JP": "ญี่ปุ่น",
          "TH_TH": "ไทย",
          "FR_CH": "ฝรั่งเศส",
          "PT_BR": "โปรตุเกส",
          "TIAO": "TIAO",
          "YONG_HU": "ผู้ใช้",
          "YI_QJRZYY_ZHOU": "มาร่วมเข้าสู่จักรวาลเสรีด้วยกัน",
          "XING_Q_LIU": "วันเสาร์",
          "QING_SRHYB_ZHU": "โปรดป้อนความคิดเห็นของเพื่อนของคุณ",
          "TUI_C_D_LU": "ออกจากระบบ",
          "QU_X_G_ZHU": "เลิกติดตาม",
          "ZHONG_XU_QI_DESC":
              "รีเลย์เปรียบเสมือนเซิร์ฟเวอร์ที่ใช้ในการจัดเก็บและดึงข้อมูล ไคลเอนต์ Freerse ถูกสร้างขึ้นบน Nostr ซึ่งมีการกระจายอำนาจและมีรีเลย์จำนวนมากที่ให้บริการจัดเก็บข้อมูลและเรียกค้น คุณเพิ่ม ข้อมูลของคุณจะถูกส่งและ สำรองข้อมูลบนรีพีทเตอร์มากเท่าที่คุณมี และคุณสามารถเพิ่มรีพีทเตอร์ที่คุณต้องการได้",
          "TIAN_JIA": "เพิ่ม",
          "COPY_DESC":
              "การละเมิด EULA นี้ รวมถึงเนื้อหาและพฤติกรรมต้องห้ามที่อธิบายไว้ข้างต้น อาจส่งผลให้การเข้าถึงแอปพลิเคชันของเราสิ้นสุดลง",
          "CHUANG_JNDZ_HU": "สร้างบัญชีของคุณ",
          "SI_YUE": "คีย์ส่วนตัว",
          "TIAN_JNDSDQBD_ZHI": "เพิ่มที่อยู่กระเป๋าเงิน Lightning ของคุณ",
          "TOU_XIANG": "อวาตาร์",
          "TIAN_JNDRZW_ZHI": "เพิ่ม URL การรับรอง NIP-05 ของคุณ",
          "WO": "ฉัน",
          "BAO_CUN": "บันทึก",
          "QING_ZZLSRB_TI": "โปรดป้อนชื่อที่นี่",
          "ZHANG_HAO": "บัญชี: ",
          "CU_ZDN_RONG":
              "เนื้อหาที่ส่งเสริมการใช้หรือการขายสารที่ผิดกฎหมายหรือควบคุม ผลิตภัณฑ์ยาสูบ กระสุน และ/หรืออาวุธปืน",
          "ZAI_NDGRZLZTJJ_JIE": "เพิ่มข้อมูลแนะนำในโปรไฟล์ของคุณ",
          "TONG_ZHI": "การแจ้งเตือน",
          "DI_ZHI": "ที่อยู่",
          "YONG_H_MING": "ชื่อผู้ใช้",
          "JIA_RHM_DAN": "เพิ่มไปยังบัญชีดำ",
          "XING_Q_ER": "วันอังคาร",
          "NI_YSCZGZJQ_MA": "คุณต้องการลบตัวทำซ้ำนี้หรือไม่",
          "SHU_YNZJDSJW_LUO": "โซเชียลเน็ตเวิร์กของคุณเอง",
          "LA_HEI": "บล็อกผู้ใช้",
          "YI_Z_FA": "ส่งต่อ",
          "ZHANG_HMMS_YUE": "รหัสส่วนตัวของรหัสผ่านบัญชี",
          "ZE_REN": "ความรับผิดชอบ",
          "เทียน": "เทียน",
          "ZHUAN_ZHANG": "โอน",
          "MING_ZBNW_KONG": "ชื่อไม่สามารถเว้นว่างได้",
          "SHU_RZJQDD_ZHI": "ป้อนที่อยู่ของทวนสัญญาณ",
          "TIAN_JNDM_ZI": "เพิ่มชื่อของคุณ",
          "DENG_LU": "เข้าสู่ระบบ",
          "WEN_ZHANG": "บทความ",
          "XING_Q_WU": "วันศุกร์",
          "NONE_ZZYHXKXY_NONE": "ข้อตกลงสิทธิ์การใช้งานสำหรับผู้ใช้ปลายทาง",
          "ZHANG_HG_YUE_1": "รหัสสาธารณะรหัสบัญชี",
          "YI_CSC_JIA": "ลบรายการโปรด",
          "SAO_Y_S_MA": "สแกนโค้ด",
          "YI_TJZJ_QI": "เพิ่มรีพีทเตอร์แล้ว",
          "FU_ZTW_NONE": "คัดลอกรหัสโพสต์",
          "C_DELETE": "ลบ",
          "TIAN_JFMTPCCW_NONE": "เพิ่มขนาดภาพหน้าปกเป็น 2.35:1",
          "FA_Q_Q_LIAO": "เริ่มการแชทเป็นกลุ่ม",
          "FEN_ZHONG": "นาที",
          "FU_Z_C_GONG": "คัดลอกสำเร็จ!",
          "SHOU_CANG": "คอลเลกชัน",
          "FA_BU": "ปล่อย",
          "FA_SONG": "ส่ง",
          "BIAO_QIAN": "ป้ายกำกับ",
          "KONG_HWXMCSRHQLTRSHWCN_REN":
              "* ข่มขู่ ข่มขู่ แอบอ้าง คุกคามหรือกลั่นแกล้งผู้อื่น ทำร้ายผู้เยาว์",
          "SHOU_D_NONE": "ได้รับ 500 SAT",
          "SHE_Z_B_ZHU": "ตั้งบันทึก",
          "BIAO_JWCWZ_NONE": "ทำเครื่องหมายว่าบทความยาว√",
          "WEI_G_H_GUO": "ผลที่ตามมาจากการละเมิด",
          "SHE_ZHI": "การตั้งค่า",
          "CHI_C_NONE": "ขนาด 2.5:1",
          "XUAN_ZWZL_XING": "เลือกประเภทบทความ",
          "GE_R_Z_LIAO": "ข้อมูลส่วนบุคคล",
          "TUI_W_X_QING": "Freerseพิ่มเติม",
          "TI_SHI": "คำแนะนำ",
          "QIAN_BAO": "กระเป๋าสตางค์",
          "ZUI_ZYHXKX_YI": "ข้อตกลงสิทธิ์การใช้งานสำหรับผู้ใช้ปลายทาง",
          "DIAN_JI": "Zap",
          "SHAN_D_F_PIAO": "ใบแจ้งหนี้ไลท์นิ่ง",
          "SHAN_DQBD_ZHI": "ที่อยู่กระเป๋าเงินไลท์นิ่ง",
          "คอง": "คอง",
          "SAO_Y_SAO": "สแกน",
          "JIN_ZNRHX_WEI": "เนื้อหาและความประพฤติต้องห้าม",
          "YU_DBYGDFFN_RONG": "* เนื้อหาที่เกี่ยวข้องกับการพนันที่ผิดกฎหมาย;",
          "WO_D_S_CANG": "คอลเลกชันของฉัน",
          "XING_Q_SI": "วันพฤหัสบดี",
          "QU_XIAO": "ยกเลิก",
          "BAN_B_NONE": "เวอร์ชัน ",
          "TIAN_JXDZJ_QI": "เพิ่มรีพีเตอร์ใหม่",
          "ZHONG_J_QI": "รีพีทเตอร์",
          "REN_MEN": "ผู้คน",
          "QUAN_Q_T_WEN": "ทั่วโลก",
          "ZHENG_C_F_BU": "ปล่อยปกติ",
          "COPY_DESC_10":
              "* เนื้อหาที่ละเมิดสิทธิ์ของบุคคลที่สาม รวมถึงลิขสิทธิ์ เครื่องหมายการค้า ความเป็นส่วนตัว การเผยแพร่ หรือสิทธิ์ส่วนบุคคลหรือกรรมสิทธิ์อื่น ๆ หรือเป็นการหลอกลวงหรือฉ้อโกง",
          "HUI_FU_2": "ตอบกลับ:",
          "TIAN_JZYB_JING": "เพิ่มพื้นหลังหน้าแรก",
          "TUI_W_LIAN": "Freerse โซ่อิสระ",
          "LIAN_X_REN": "ติดต่อ",
          "ZHI_FU": "การชำระเงิน",
          "TIE_ZJTBDWZX_SHI": "โพสต์จะถูกซิงโครไนซ์กับการแสดงบทความ",
          "BAO_LIU_QUANLI":
              "เราขอสงวนสิทธิ์ในการแก้ไข EULA นี้ได้ตลอดเวลาโดยไม่ต้องแจ้งให้ทราบล่วงหน้า การใช้แอปพลิเคชันของคุณต่อไปหลังจากการโพสต์ EULA ที่แก้ไขใด ๆ บ่งชี้ว่าคุณยอมรับข้อกำหนดของ EULA ที่แก้ไขแล้ว",
          "TONG_YBJ_XU": "ตกลงและดำเนินการต่อ",
          "XING_Q_TIAN": "วันอาทิตย์",
          "SOU_SUO": "ค้นหา",
          "REN_ZHENG": "ใบรับรอง",
          "PRI_DESC":
              "คีย์ส่วนตัวคือรหัสผ่านบัญชีของคุณ หากคุณทำคีย์ส่วนตัวหาย คุณจะไม่สามารถเข้าถึงบัญชีของคุณได้! ไม่มีทางที่จะดึงคีย์ส่วนตัวกลับมาได้ เก็บคีย์ส่วนตัวของคุณไว้และอย่าเปิดเผยให้ใครรู้ . ประชากร.",
          "TIAN_JNDW_ZHAN": "เพิ่มเว็บไซต์ของคุณ",
          "TUI_WYH_FU": "บกลับ",
          "WEN_ZDYX_XI": "ข้อความสมัครรับบทความ",
          "COPY_DESC_12":
              "ข้อตกลงสิทธิ์การใช้งานสำหรับผู้ใช้ปลายทาง (EULA) นี้เป็นข้อตกลงทางกฎหมายระหว่างคุณและ Freerse Inc. เกี่ยวกับการใช้แอปพลิเคชันมือถือ Freerse โดยการติดตั้ง เข้าถึง หรือใช้แอปพลิเคชันของเรา แสดงว่าคุณตกลงที่จะผูกพันตาม ข้อกำหนดของข้อกำหนดและเงื่อนไข EULA นี้ หากคุณไม่ยอมรับ EULA นี้ คุณจะไม่สามารถใช้แอปของเราได้",
          "TIAN_XNDZHS_YUE": "กรอกรหัสส่วนตัวของบัญชีของคุณ",
          "CHUANG_J_Z_HU": "สร้าง",
          "QING_XTYX_YI": "โปรดยอมรับข้อตกลงก่อน",
          "TIAN_JDSC_JIA": "เพิ่มเข้ารายการโปรด",
          "XING_Q_SAN": "วันพุธ",
          "FU_ZYHG_YUE": "คัดลอกรหัสสาธารณะ ID ผู้ใช้",
          "WANG_ZHAN": "เว็บไซต์",
          "LA_HCY_HU": "บล็อกผู้ใช้รายนี้",
          "SOU_S_NONE": "ค้นหา Freeres",
          "XING_Q_YI": "วันจันทร์",
          "ZHANG_HG_YUE": "รหัสสาธารณะรหัสบัญชี",
          "YI_YDBT_YI": "อ่านและยอมรับ",
          "WO_YJBCLWDMMS_YUE": "ฉันได้บันทึกรหัสส่วนตัวของรหัสผ่านแล้ว",
          "SHOU_F_KUAN": "การชำระเงิน",
          "FU_Z_W_BEN": "คัดลอกข้อความ",
          "GONG_YUE": "รหัสสาธารณะ",
          "COPY_DESC_11":
              "แอปของเราให้บริการ ตามสภาพ และ ตามที่มี โดยไม่มีการรับประกันใดๆ ทั้งโดยชัดแจ้งหรือโดยนัย รวมถึงแต่ไม่จำกัดเพียงการรับประกันโดยนัยต่อความสามารถเชิงพาณิชย์และความเหมาะสมสำหรับวัตถุประสงค์เฉพาะ เราทำ ไม่รับประกันว่าแอพของเราโปรแกรมจะไม่หยุดชะงักหรือปราศจากข้อผิดพลาด ไม่ว่าในกรณีใด Freerse Inc. จะไม่รับผิดชอบต่อความเสียหายใด ๆ ที่เกิดขึ้นจากหรือเกี่ยวข้องกับการใช้หรือการไม่สามารถใช้แอปพลิเคชันของเรา รวมถึง แต่ ไม่จำกัดเฉพาะความเสียหายทางตรง ทางอ้อม ความเสียหายพิเศษ โดยบังเอิญ หรือเป็นผลสืบเนื่อง",
          "ZUO_TIAN": "เมื่อวาน",
          "DAI_YQSXSDBLXYCHY_LUN":
              "* เลือกปฏิบัติ ยุยงให้เกิดความรุนแรง และส่งเสริมคำพูดแสดงความเกลียดชัง;",
          "NIN_TYBJYYJZDNRHXWBKDBX_YU":
              "คุณตกลงที่จะไม่ใช้ Freerse สำหรับเนื้อหาหรือการกระทำที่ต้องห้าม รวมถึงแต่ไม่จำกัดเพียง",
          "TIAN_J_F_WU": "เพิ่มบริการ",
          "SHUO_DSM_BA": "พูดอะไรสักอย่าง...",
          "FEN_SI": "แฟนๆ",
          "BIAN_JGRZ_LIAO": "แก้ไขข้อมูล",
          "BANG_Z_Z_XIN": "ศูนย์ช่วยเหลือ",
          "KAI_SHI": "เริ่ม",
          "YIN_HSQMFFBZSBLHHFFNRHX_DU":
              "* เนื้อหาลามกอนาจาร น่ารังเกียจ หมิ่นประมาท ใส่ร้าย รุนแรง และ/หรือผิดกฎหมาย หรือหยาบคาย;",
          "ZI_L_S_ZHI": "การตั้งค่าข้อมูล",
          "ZXQ_DI_QI":
              "จุดสีเขียวในแถวแรกแสดงถึงความแรงของสัญญาณเครือข่ายของตัวทวน สีเขียวหมายถึงสัญญาณเรียบ และสีแดงหมายถึงสัญญาณอ่อน ไอคอนในแถวที่สองที่มีไอคอน Bitcoin นั้นเป็นเครื่องทวนแบบชำระเงิน ",
          "TIAN_S_RU": "อินพุต TIAN",
          "ZHU_YBJ_TU": "ภาพพื้นหลังหน้าแรก",
          "FU_ZYHGY_NONE": "คัดลอกคีย์สาธารณะ Pubkey ของผู้ใช้",
          "CONG_ZLKSXZ_WEN": "เริ่มเขียนข้อความจากที่นี่",
          "DIAN_ZAN": "ถูกใจ",
          "XIAO_SHI": "ชั่วโมง",
          "GUAN_Y_WO": "เกี่ยวกับฉัน",
          "ZHAO_PIAN": "ภาพถ่าย",
          "BAO_CNDS_YUE": "บันทึกคีย์ส่วนตัวของคุณ",
          "BIAO_ZWCW_ZHANG": "ทำเครื่องหมายว่าเป็นบทความยาว",
          "MIAO": "วินาที",
          "TUI_WEN": "อิสระ",
          "YU_LAN": "ดูตัวอย่าง",
          "QU_X_L_HEI": "ยกเลิกบัญชีดำ",
          "RU_GNDCYRHYWQTGYWML_XI":
              "หากคุณมีคำถามใดๆ เกี่ยวกับ EULA นี้ โปรดติดต่อเราที่ freerse8@gmail.com",
          "TIAN_JNDYH_MING": "เพิ่มชื่อผู้ใช้ของคุณ",
          "JIE_S_T_KUAN": "ยอมรับเงื่อนไข",
          "BIAO_JWTW_NONE": "รีลีสปกติ",
          "ZHI_D_L_TIAN": "แชทยอดนิยม",
          "JIE_SHOU": "ยอมรับ",
          "GUAN_ZHU": "ติดตาม",
          "MING_ZI": "ชื่อ",
          "HUI_FU": "ตอบกลับ",
          "LISENCE_ACCEPT_DESC1":
              "การใช้แอปของเรา แสดงว่าคุณยอมรับ EULA นี้ หากคุณไม่ยอมรับ EULA นี้ คุณจะไม่สามารถใช้แอปของเราได้",
          "QING_XQRYJBCMMS_YUE":
              "โปรดยืนยันว่ารหัสส่วนตัวของรหัสผ่านได้รับการบันทึกไว้ก่อน",
          "XIAO_XI": "ข้อความ",
          "LIAN_X_F_SHI": "ข้อมูลติดต่อ",
          "BA_TTJGP_YOU": "แนะนำเขาให้เพื่อน",
          "TIAN_J_C_GONG": "เพิ่มเรียบร้อยแล้ว!",
          "TIE_ZI": "อิสระ",
          "ZHUAN_FA": "ไปข้างหน้า",
          "FA_XIAN": "ค้นพบ",
          "GUAN_Y_NONE": "เกี่ยวกั Freerse",
          "XIN_D_P_YOU": "เพื่อนใหม่",
          "GONG_YSNGZ_NI":
              "รหัสสาธารณะคือรหัสบัญชีของคุณ คุณสามารถคัดลอกและส่งให้เพื่อนของคุณซึ่งสามารถค้นหาและติดตามคุณผ่านรหัสสาธารณะได้",
          "BIAN_G_NONE": "เปลี่ยน EULA",
          "NIP_AUTH": "การรับรองความถูกต้อง NIP-05",
          "JUBAO": "รายงาน",
          "JUBAO_OK": "รายงานสำเร็จ",
          "JUBAO_LJ": "เนื้อหาขยะ",
          "JUBAO_LT": "ภาพเปลือยหรือเนื้อหาที่โจ่งแจ้ง",
          "JUBAO_WG": "เนื้อหาที่ผิดกฎหมาย",
          "DELETE_ACCOUNT": "ลบบัญชี",
          "DELETE_ACCOUNT_TIP":
              "คุณจะลบข้อมูลบัญชีของคุณ และข้อมูลบัญชีของคุณทั้งหมดจะสูญหาย คุณแน่ใจหรือไม่ว่าต้องการลบบัญชีของคุณต่อไป",
          "SHOW_MORE": "แสดงเพิ่มเติม",
          "ZAP_WALLET": "กระเป๋าเงินไลท์นิ่ง",
          "IMAGE": "ภาพ",
          "ZAP_CONNECT_TIP":
              "วางหรือป้อนรหัสสาธารณะ, Relay และ Wallet Connect Secret รองรับเฉพาะกระเป๋าเงินที่ปรับให้เข้ากับโปรโตคอล Nostr Wallet Connect เท่านั้น",
          "PASTE_OR_ENTER_HERE": "กรุณาวางหรือป้อนที่นี่",
          "PASTE": "วาง",
          "CLEAR": "ชัดเจน",
          "CONNECT_WALLET": "เชื่อมต่อกระเป๋าเงิน",
          "SCAN_QR_CODE": "สแกนโค้ด QR",
          "CONNECT_OTHER_WALLETS": "เชื่อมต่อกระเป๋าเงินอื่น",
          "OTHER_AMOUNT": "จำนวนเงินอื่น",
          "PLEASE_INPUT_AMOUNT": "โปรดป้อนจำนวน",
          "MESSAGE": "ข้อความ",
          "PLEASE_INPUT_MESSAGE": "กรุณากรอกข้อความ",
          "CONFIRM": "ตกลง",
          "DEFAULT_ZAP_AMOUNT_IN_SATS": "จำนวน Zap เริ่มต้น มีหน่วยเป็น sats",
          "ZAP_AMOUNT_TIP":
              "1 Bitcoin = 100,000,000 sats คลิก Zap เพื่อส่งจำนวนเงินเริ่มต้น กดปุ่ม Zap ค้างไว้เพื่อส่งจำนวนเงินที่กำหนดเอง",
          "SET_CUSTOM_ZAP_AMOUNT": "กำหนดจำนวน Zap ที่กำหนดเอง",
          "RESTORE_DEFAULT_SETTINGS": "คืนค่าการตั้งค่าเริ่มต้น",
          "ZAP_AMOUNT_SETTINGS": "การตั้งค่าจำนวน Zap",
          "BITCOIN_LIGHTNING_WALLET": "กระเป๋าสตางค์สายฟ้า Bitcoin",
          "ZAP_RECEIVE_SEND_TIP":
              "หากต้องการส่งและรับ Zap โปรดเชื่อมต่อกระเป๋าเงิน Bitcoin Lightning",
          "ZAP_DES": "Zap ใช้ Bitcoin เพื่อให้รางวัลแก่โพสต์ที่คุณชอบ",
          "ALBY_BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "เชื่อมต่อ Alby Bitcoin Lightning Wallet แล้ว",
          "BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "เชื่อมต่อ Bitcoin Lightning Wallet แล้ว",
          "DISCONNECT_WALLET": "ยกเลิกการเชื่อมต่อกระเป๋าเงิน",
          "CONNECT_ALBY_WALLET": "เชื่อมต่อกระเป๋าเงิน Alby",
          "DISCONNECT_TIP":
              "กระเป๋าเงินที่ถูกตัดการเชื่อมต่อจะไม่สามารถส่ง zap ได้ ที่อยู่กระเป๋าเงินนี้ยังสามารถรับ zap ได้ หากคุณต้องการแก้ไขที่อยู่กระเป๋าเงิน โปรดแก้ไขในข้อมูลส่วนตัวของคุณ",
          "ZAP_SENDING": "ส่ง Zap",
          "NO_WALLET_WAS_FOUND": "ไม่พบกระเป๋าเงิน",
          "THIS_ACCOUNT_DOES_NOT_HAVE_A_WALLET_ADDRESS_SET":
              "บัญชีนี้ไม่ได้ตั้งค่าที่อยู่กระเป๋าเงินไว้",
          "QUOTE": "อ้างอิง",
          "DONATE": "บริจาค",
          "DONATE_DES1": "สนับสนุน Freerse",
          "DONATE_DES2": "ช่วยสร้างเครือข่ายโซเชียลที่มีการกระจายอำนาจ",
          "RETWEETED": "รีทวีตแล้ว",
          "ZAPED": "ZAPED",
          "REACTED": "ชอบ",
          "AND": "และ",
          "OTHERS": "อื่นๆ",
          "YOUR_FREERSE": "อิสระของคุณ",
          "YOU": "คุณ",
          "H_Y_S_Q_X_X": "ข้อความสมัครเป็นเพื่อน",
          "SAVE_IMAGE_SUCCESS": "บันทึกลงในอัลบั้ม",
          "LOADING": "กำลังโหลด",
          "FAILED_TO_SEND": "การส่งล้มเหลว",
          "THANKS_DONATE": "ขอบคุณสำหรับการบริจาค",
          "ZAP_FAIL": "Zap ล้มเหลว",
          "DONATE1_NAME": "Freerse บริจาคฟรี 1",
          "DONATE2_NAME": "Freerse บริจาคฟรี 2",
          "DONATE3_NAME": "Freerse บริจาคฟรี 3",
          "DONATE4_NAME": "Freerse บริจาคฟรี 4",
          "COPY": "คัดลอก",
          "HOT": "ร้อนร้อน"
        },
        'fr_CH': {
          "OUT_APP_TIP": "Presione nuevamente para salir de la aplicación.",
          "SET_ACCOUNT": "Compte",
          "GUAN_ZHU": "Suivre",
          "QU_SHI": "Tendance 24h",
          "MENU_THEME": "Apparence",
          "MENU_LOCAL": "Multi-langue",
          "SET_THEME": "Définir le thème",
          "THEME_AUTO": "Suivez le système",
          "THEME_LIGHT": "Couleur de la lumière",
          "THEME_DARK": "Sombre",
          "SET_LOCAL": "Définir la langue",
          "EN_US": "Anglais",
          "ZH_CN": "Chinois simplifié",
          "ZH_TW": "Chinois traditionnel",
          "JA_JP": "Japonais",
          "TH_TH": "Thaï",
          "FR_CH ": "Français",
          "PT_BR ": "Portugais",
          "TIAO": "TIAO",
          "YONG_HU": "Utilisateur",
          "YI_QJRZYY_ZHOU": "Entrons ensemble dans l'univers libre",
          "XING_Q_LIU": "Samedi",
          "QING_SRHYB_ZHU": "Veuillez saisir les remarques de votre ami",
          "TUI_C_D_LU": "Déconnexion",
          "QU_X_G_ZHU": "Ne plus suivre",
          "ZHONG_XU_QI_DESC":
              "Un relais est comme un serveur, utilisé pour stocker et récupérer des données. Le client Freerse est créé sur Nostr, qui est décentralisé et dispose de nombreux relais qui fournissent des services de stockage et de récupération de données. Vous ajoutez Vos données seront transmises et sauvegardé sur autant de répéteurs que vous en avez, et vous pouvez ajouter les répéteurs de votre choix.",
          "TIAN_JIA": "Ajouter",
          "COPY_DESC":
              "Toute violation de ce CLUF, y compris le contenu et le comportement interdits décrits ci-dessus, peut entraîner la résiliation de votre accès à notre Application.",
          "CHUANG_JNDZ_HU": "Créez votre compte",
          "SI_YUE": "Clé privée",
          "TIAN_JNDSDQBD_ZHI":
              "Ajoutez l'adresse de votre portefeuille Lightning",
          "TOU_XIANG": "Avatar",
          "TIAN_JNDRZW_ZHI": "Ajoutez votre URL de certification NIP-05",
          "WO": "Je",
          "BAO_CUN": "Enregistrer",
          "QING_ZZLSRB_TI": "Veuillez entrer un titre ici",
          "ZHANG_HAO": "Compte : ",
          "CU_ZDN_RONG":
              "Contenu faisant la promotion de l'utilisation ou de la vente de substances illégales ou contrôlées, de produits du tabac, de munitions et/ou d'armes à feu ;",
          "ZAI_NDGRZLZTJJ_JIE": "Ajouter une introduction à votre profil",
          "TONG_ZHI": "Notifications",
          "DI_ZHI": "Adresse",
          "YONG_H_MING": "Nom d'utilisateur",
          "JIA_RHM_DAN": "Ajouter à la liste noire",
          "XING_Q_ER": "Mardi",
          "NI_YSCZGZJQ_MA": "Voulez-vous supprimer ce répéteur ?",
          "SHU_YNZJDSJW_LUO": "Votre propre réseau social",
          "LA_HEI": "Bloquer l'utilisateur",
          "YI_Z_FA": "Transféré",
          "ZHANG_HMMS_YUE": "Clé privée du mot de passe du compte",
          "ZE_REN": "Responsabilité",
          "TIAN": "天",
          "ZHUAN_ZHANG": "Transfert",
          "MING_ZBNW_KONG": "Le nom ne peut pas être vide",
          "SHU_RZJQDD_ZHI": "Entrez l'adresse du répéteur",
          "TIAN_JNDM_ZI": "Ajoutez votre nom",
          "DENG_LU": "Connexion",
          "WEN_ZHANG": "article",
          "XING_Q_WU": "Vendredi",
          "NONE_ZZYHXKXY_NONE": "Contrat de licence utilisateur final",
          "ZHANG_HG_YUE_1": "Clé publique de l'ID de compte",
          "YI_CSC_JIA": "Supprimer les favoris",
          "SAO_Y_S_MA": "Scannez le code",
          "YI_TJZJ_QI": "Répéteur ajouté",
          "FU_ZTW_NONE": "Copier l'ID de la publication",
          "C_DELETE": "Supprimer",
          "TIAN_JFMTPCCW_NONE":
              "Ajouter la taille de l'image de couverture à 2,35:1",
          "FA_Q_Q_LIAO": "Démarrer une discussion de groupe",
          "FEN_ZHONG": "minutes",
          "FU_Z_C_GONG": "Copie réussie !",
          "SHOU_CANG": "Collection",
          "FA_BU": "Libérer",
          "FA_SONG": "Envoyer",
          "BIAO_QIAN": "étiquette",
          "KONG_HWXMCSRHQLTRSHWCN_REN":
              "* Intimider, menacer, usurper l'identité, harceler ou intimider autrui, nuire à des mineurs ;",
          "SHOU_D_NONE": "Reçu 500 SAT",
          "SHE_Z_B_ZHU": "Définir des notes",
          "BIAO_JWCWZ_NONE": "Marquer comme article long√",
          "WEI_G_H_GUO": "Conséquences d'une violation",
          "SHE_ZHI": "Paramètres",
          "CHI_C_NONE": "Taille 2,5:1",
          "XUAN_ZWZL_XING": "Sélectionner le type d'article",
          "GE_R_Z_LIAO": "Informations personnelles",
          "TUI_W_X_QING": "Freerse Détails",
          "TI_SHI": "Astuce",
          "QIAN_BAO": "portefeuille",
          "ZUI_ZYHXKX_YI": "Contrat de licence utilisateur final",
          "DIAN_JI": "Zap",
          "SHAN_D_F_PIAO": "Facture Lightning",
          "SHAN_DQBD_ZHI": "Adresse du portefeuille Lightning",
          "CONG": "Cong",
          "SAO_Y_SAO": "Analyser",
          "JIN_ZNRHX_WEI": "Contenu et comportement interdits",
          "YU_DBYGDFFN_RONG": "* Contenu illégal lié aux jeux d'argent ;",
          "WO_D_S_CANG": "Ma Collection",
          "XING_Q_SI": "Jeudi",
          "QU_XIAO": "Annuler",
          "BAN_B_NONE": "Version ",
          "TIAN_JXDZJ_QI": "Ajouter un nouveau répéteur",
          "ZHONG_J_QI": "Répéteur",
          "REN_MEN": "personnes",
          "QUAN_Q_T_WEN": "Global",
          "ZHENG_C_F_BU": "Version normale",
          "COPY_DESC_10":
              "* Contenu qui enfreint les droits d'un tiers, y compris les droits d'auteur, les marques déposées, la vie privée, la publicité ou d'autres droits personnels ou de propriété, ou qui est trompeur ou frauduleux ;",
          "HUI_FU_2": "Réponse :",
          "TIAN_JZYB_JING": "Ajouter un arrière-plan de la page d'accueil",
          "TUI_W_LIAN": "Freerse Chaîne",
          "LIAN_X_REN": "Contact",
          "ZHI_FU": "Paiement",
          "TIE_ZJTBDWZX_SHI":
              "Les publications seront synchronisées avec l'affichage des articles",
          "BAO_LIU_QUANLI":
              "Nous nous réservons le droit de modifier ce CLUF à tout moment sans préavis. Votre utilisation continue de l'Application après la publication de tout CLUF modifié indique votre acceptation des termes du CLUF modifié.",
          "TONG_YBJ_XU": "Accepter et continuer",
          "XING_Q_TIAN": "Dimanche",
          "SOU_SUO": "Rechercher",
          "REN_ZHENG": "Certification",
          "PRI_DESC":
              "La clé privée est le mot de passe de votre compte. Si vous perdez votre clé privée, vous ne pourrez pas accéder à votre compte ! Il n'y a aucun moyen de récupérer la clé privée. Conservez votre clé privée et ne la divulguez jamais à personne . personnes.",
          "TIAN_JNDW_ZHAN": "Ajoutez votre site Web",
          "TUI_WYH_FU": "répondre",
          "WEN_ZDYX_XI": "Message d'abonnement à l'article",
          "COPY_DESC_12":
              "Ce contrat de licence utilisateur final ('CLUF') est un accord juridique entre vous et Freerse Inc. concernant l'utilisation de l'application mobile Freerse. En installant, en accédant ou en utilisant notre application, vous acceptez d'être lié par le termes des présentes conditions générales du CLUF. Si vous n'acceptez pas ce CLUF, vous ne pouvez pas utiliser notre application.",
          "TIAN_XNDZHS_YUE": "Renseignez la clé privée de votre compte",
          "CHUANG_J_Z_HU": "Créer",
          "QING_XTYX_YI": "Veuillez d'abord accepter l'accord",
          "TIAN_JDSC_JIA": "Ajouter aux Favoris",
          "XING_Q_SAN": "Mercredi",
          "FU_ZYHG_YUE": "Copier la clé publique de l'ID utilisateur",
          "WANG_ZHAN": "Site Web",
          "LA_HCY_HU": "Bloquer cet utilisateur",
          "SOU_S_NONE": "Rechercher des Freeres",
          "XING_Q_YI": "Lundi",
          "ZHANG_HG_YUE": "Clé publique de l'ID de compte",
          "YI_YDBT_YI": "Lire et accepter",
          "WO_YJBCLWDMMS_YUE":
              "J'ai enregistré la clé privée de mon mot de passe",
          "SHOU_F_KUAN": "Paiement",
          "FU_Z_W_BEN": "Copier le texte",
          "GONG_YUE": "Clé publique",
          "COPY_DESC_11":
              "Nos applications sont fournies telles quelles et 'telles que disponibles' sans garantie d'aucune sorte, expresse ou implicite, y compris, mais sans s'y limiter, les garanties implicites de qualité marchande et d'adéquation à un usage particulier. Nous le faisons ne garantit pas que nos applications Le programme sera ininterrompu ou sans erreur. En aucun cas Freerse Inc. ne sera responsable de tout dommage de quelque nature que ce soit découlant de ou en relation avec l'utilisation ou l'incapacité d'utiliser notre application, y compris, mais sans s'y limiter, les dommages directs, indirects, spéciaux, accessoires ou consécutifs. ",
          "ZUO_TIAN": "Hier",
          "DAI_YQSXSDBLXYCHY_LUN":
              "* Discriminatoire, incitation à la violence et promotion du discours de haine ;",
          "NIN_TYBJYYJZDNRHXWBKDBX_YU":
              "Vous acceptez de ne pas utiliser Freerse pour un contenu ou un comportement interdit, y compris, mais sans s'y limiter",
          "TIAN_J_F_WU": "Ajouter un service",
          "SHUO_DSM_BA": "Dites quelque chose...",
          "FEN_SI": "Ventilateurs",
          "BIAN_JGRZ_LIAO": "Modifier les informations",
          "BANG_Z_Z_XIN": "Centre d'aide",
          "KAI_SHI": "Démarrer",
          "YIN_HSQMFFBZSBLHHFFNRHX_DU":
              "* Contenu ou grossièretés obscènes, pornographiques, offensants, diffamatoires, calomnieux, violents et/ou illégaux ;",
          "ZI_L_S_ZHI": "Paramètres des données",
          "ZXQ_DI_QI":
              "Les points verts dans la première rangée représentent la force du signal réseau du répéteur. Le vert signifie un signal lisse et le rouge signifie un signal faible. Les icônes de la deuxième rangée avec l'icône Bitcoin sont des répéteurs payants. ",
          "TIAN_S_RU": "Entrée TIAN",
          "ZHU_YBJ_TU": "Image d'arrière-plan de la page d'accueil",
          "FU_ZYHGY_NONE": "Copiez la clé publique Pubkey de l'utilisateur",
          "CONG_ZLKSXZ_WEN": "Commencez à écrire le texte à partir d'ici",
          "DIAN_ZAN": "J'aime",
          "XIAO_SHI": "heure",
          "GUAN_Y_WO": "À propos de moi",
          "ZHAO_PIAN": "Photo",
          "BAO_CNDS_YUE": "Enregistrez votre clé privée",
          "BIAO_ZWCW_ZHANG": "Marquer comme article long",
          "MIAO": "secondes",
          "TUI_WEN": "Libérer",
          "YU_LAN": "Aperçu",
          "QU_X_L_HEI": "Annuler la liste noire",
          "RU_GNDCYRHYWQTGYWML_XI":
              "Si vous avez des questions sur ce CLUF, veuillez nous contacter à freerse8@gmail.com.",
          "TIAN_JNDYH_MING": "Ajoutez votre nom d'utilisateur",
          "JIE_S_T_KUAN": "Accepter les conditions",
          "BIAO_JWTW_NONE": "Version normale",
          "ZHI_D_L_TIAN": "Meilleure discussion",
          "JIE_SHOU": "Accepter",
          "GUAN_ZHU": "Suivre",
          "MING_ZI": "nom",
          "HUI_FU": "Répondre",
          "LISENCE_ACCEPT_DESC1":
              "En utilisant notre application, vous acceptez ce CLUF. Si vous n'acceptez pas ce CLUF, vous ne pouvez pas utiliser notre application.",
          "QING_XQRYJBCMMS_YUE":
              "Veuillez d'abord confirmer que la clé privée du mot de passe a été enregistrée",
          "XIAO_XI": "Message",
          "LIAN_X_F_SHI": "Coordonnées",
          "BA_TTJGP_YOU": "Recommandez-le à vos amis",
          "TIAN_J_C_GONG": "Ajouté avec succès !",
          "TIE_ZI": "Libérer",
          "ZHUAN_FA": "En avant",
          "FA_XIAN": "Découvrir",
          "GUAN_Y_NONE": "À propos de Freerse",
          "XIN_D_P_YOU": "Nouveaux amis",
          "GONG_YSNGZ_NI":
              "La clé publique est votre identifiant de compte. Vous pouvez la copier et l'envoyer à vos amis, qui pourront vous rechercher et vous suivre grâce à la clé publique.",
          "BIAN_G_NONE": "Modifier le CLUF",
          "NIP_AUTH": "Authentification NIP-05",
          "JUBAO": "Rapport",
          "JUBAO_OK": "Rapport réussi",
          "JUBAO_LJ": "Contenu indésirable",
          "JUBAO_LT": "Nudité ou contenu explicite",
          "JUBAO_WG": "Contenu illégal",
          "DELETE_ACCOUNT": "Supprimer le compte",
          "DELETE_ACCOUNT_TIP":
              "Vous allez supprimer les informations de votre compte et vous perdrez toutes les informations de votre compte. Êtes-vous sûr de vouloir continuer à supprimer votre compte ?",
          "SHOW_MORE": "Afficher plus",
          "ZAP_WALLET": "Portefeuille Lightning",
          "IMAGE": "image",
          "ZAP_CONNECT_TIP":
              "Collez ou saisissez la clé publique, Relay et Wallet Connect Secret. Seuls les portefeuilles adaptés au protocole Nostr Wallet Connect sont pris en charge.",
          "PASTE_OR_ENTER_HERE": "Veuillez coller ou saisir ici",
          "PÂTE": "Coller",
          "CLAIR": "CLAIR",
          "CONNECT_WALLET": "Connecter le portefeuille",
          "SCAN_QR_CODE": "Scanner le code QR",
          "CONNECT_OTHER_WALLETS": "Connecter d'autres portefeuilles",
          "OTHER_AMOUNT": "Autre montant",
          "PLEASE_INPUT_AMOUNT": "Veuillez saisir la quantité",
          "MESSAGE": "Message",
          "PLEASE_INPUT_MESSAGE": "Veuillez saisir un message",
          "CONFIRMER": "OK",
          "DEFAULT_ZAP_AMOUNT_IN_SATS": "Montant de Zap par défaut, en sats.",
          "ZAP_AMOUNT_TIP":
              "1 Bitcoin = 100 000 000 sats, cliquez sur Zap pour envoyer le montant par défaut, appuyez longuement sur le bouton Zap pour envoyer un montant personnalisé.",
          "SET_CUSTOM_ZAP_AMOUNT": "Définir un montant de Zap personnalisé",
          "RESTORE_DEFAULT_SETTINGS": "Restaurer les paramètres par défaut",
          "ZAP_AMOUNT_SETTINGS": "Paramètres du montant du Zap",
          "BITCOIN_LIGHTNING_WALLET": "Portefeuille Bitcoin Lightning",
          "ZAP_RECEIVE_SEND_TIP":
              "Pour envoyer et recevoir Zap, veuillez connecter un portefeuille Bitcoin Lightning.",
          "ZAP_DES":
              "Zap utilise Bitcoin pour récompenser les publications que vous aimez.",
          "ALBY_BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "Alby Bitcoin Lightning Wallet est connecté",
          "BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "Le portefeuille Bitcoin Lightning est connecté",
          "DISCONNECT_WALLET": "Déconnecter le portefeuille",
          "CONNECT_ALBY_WALLET": "Connecter le portefeuille Alby",
          "DISCONNECT_TIP":
              "Le portefeuille déconnecté ne pourra pas envoyer de zap. Cette adresse de portefeuille peut également recevoir du zap. Si vous devez modifier l'adresse du portefeuille, veuillez la modifier dans vos informations personnelles.",
          "ZAP_SENDING": "Envoi Zap",
          "NO_WALLET_WAS_FOUND": "Portefeuille introuvable.",
          "THIS_ACCOUNT_DOES_NOT_HAVE_A_WALLET_ADDRESS_SET":
              "Ce compte n'a pas d'adresse de portefeuille définie.",
          "CITATION": "Citation",
          "FAIRE UN DON": "Faire un don",
          "DONATE_DES1": "Supportez Freerse",
          "DONATE_DES2": "Aidez à créer des réseaux sociaux décentralisés.",
          "RETWEETED": "Retweeté",
          "ZAPÉ": "ZAPÉ",
          "RÉAGI": "J'ai aimé",
          "AND": "ET",
          "AUTRES": "Autres",
          "YOUR_FREERSE": "votre liberté",
          "VOUS": "vous",
          "H_Y_S_Q_X_X": "Message de candidature d'ami",
          "SAVE_IMAGE_SUCCESS": "Enregistré dans l'album",
          "CHARGEMENT": "Chargement",
          "FAILED_TO_SEND": "L'envoi a échoué",
          "THANKS_DONATE": "Merci pour votre don",
          "ZAP_FAIL": "Zap a échoué",
          "DONATE1_NAME": "Freerse fait un don de 1",
          "DONATE2_NAME": "Freerse Faites un don 2",
          "DONATE3_NAME": "Freerse Faites un don de 3",
          "DONATE4_NAME": "Freerse fait un don de 4",
          "COPIER": "Copier",
          "HOT": "chaud"
        },
        'pt_BR': {
          "OUT_APP_TIP": "Pressione novamente para sair do aplicativo",
          "SET_ACCOUNT": "Conta",
          "GUAN_ZHU": "Seguir",
          "QU_SHI": "Tendência 24h",
          "MENU_THEME": "Aparência",
          "MENU_LOCAL": "Multilíngue",
          "SET_THEME": "Definir tema",
          "THEME_AUTO": "Seguir o sistema",
          "THEME_LIGHT": "Cor clara",
          "THEME_DARK": "Escuro",
          "SET_LOCAL": "Definir idioma",
          "EN_US": "Inglês",
          "ZH_CN": "Chinês Simplificado",
          "ZH_TW": "Chinês Tradicional",
          "JA_JP": "Japonês",
          "TH_TH": "Tailandês",
          "FR_CH": "Francês",
          "PT_BR": "Português",
          "TIAO": "TIAO",
          "YONG_HU": "Usuário",
          "YI_QJRZYY_ZHOU": "Vamos entrar juntos no universo livre",
          "XING_Q_LIU": "Sábado",
          "QING_SRHYB_ZHU": "Por favor insira os comentários do seu amigo",
          "TUI_C_D_LU": "Sair",
          "QU_X_G_ZHU": "Deixar de seguir",
          "ZHONG_XU_QI_DESC":
              "Um relé é como um servidor, usado para armazenar e recuperar dados. O cliente Freerse é criado no Nostr, que é descentralizado e possui muitos relés que fornecem serviços de armazenamento e recuperação de dados. Você adiciona Seus dados serão transmitidos e backup em quantos repetidores você tiver, e você pode adicionar os repetidores que desejar.",
          "TIAN_JIA": "Adicionar",
          "COPY_DESC":
              "Qualquer violação deste EULA, incluindo o conteúdo e conduta proibidos descritos acima, pode resultar no encerramento do seu acesso ao nosso Aplicativo.",
          "CHUANG_JNDZ_HU": "Crie sua conta",
          "SI_YUE": "Chave Privada",
          "TIAN_JNDSDQBD_ZHI": "Adicione o endereço da sua carteira Lightning",
          "TOU_XIANG": "Avatar",
          "TIAN_JNDRZW_ZHI": "Adicione seu URL de certificação NIP-05",
          "WO": "eu",
          "BAO_CUN": "Salvar",
          "QING_ZZLSRB_TI": "Por favor insira um título aqui",
          "ZHANG_HAO": "Conta: ",
          "CU_ZDN_RONG":
              "Conteúdo que promove o uso ou venda de substâncias ilegais ou controladas, produtos de tabaco, munições e/ou armas de fogo;",
          "ZAI_NDGRZLZTJJ_JIE": "Adicionar introdução ao seu perfil",
          "TONG_ZHI": "Notificação",
          "DI_ZHI": "Endereço",
          "YONG_H_MING": "Nome de usuário",
          "JIA_RHM_DAN": "Adicionar à lista negra",
          "XING_Q_ER": "Terça-feira",
          "NI_YSCZGZJQ_MA": "Deseja excluir este repetidor?",
          "SHU_YNZJDSJW_LUO": "Sua própria rede social",
          "LA_HEI": "Bloquear usuário",
          "YI_Z_FA": "Encaminhado",
          "ZHANG_HMMS_YUE": "Chave privada da senha da conta",
          "ZE_REN": "Responsabilidade",
          "TIAN": "天",
          "ZHUAN_ZHANG": "Transferir",
          "MING_ZBNW_KONG": "O nome não pode ficar vazio",
          "SHU_RZJQDD_ZHI": "Digite o endereço do repetidor",
          "TIAN_JNDM_ZI": "Adicione seu nome",
          "DENG_LU": "Login",
          "WEN_ZHANG": "artigo",
          "XING_Q_WU": "Sexta-feira",
          "NONE_ZZYHXKXY_NONE": "Contrato de licença do usuário final",
          "ZHANG_HG_YUE_1": "Chave pública do ID da conta",
          "YI_CSC_JIA": "Remover favoritos",
          "SAO_Y_S_MA": "Escaneie o código",
          "YI_TJZJ_QI": "Repetidor adicionado",
          "FU_ZTW_NONE": "Copiar ID da postagem",
          "C_DELETE": "Excluir",
          "TIAN_JFMTPCCW_NONE":
              "Adicionar tamanho da imagem da capa para 2,35:1",
          "FA_Q_Q_LIAO": "Iniciar um bate-papo em grupo",
          "FEN_ZHONG": "minutos",
          "FU_Z_C_GONG": "Copiar com sucesso!",
          "SHOU_CANG": "Coleção",
          "FA_BU": "Liberar",
          "FA_SONG": "Enviar",
          "BIAO_QIAN": "rótulo",
          "KONG_HWXMCSRHQLTRSHWCN_REN":
              "* Intimidar, ameaçar, personificar, assediar ou intimidar outras pessoas, prejudicar menores;",
          "SHOU_D_NONE": "Recebido 500 SAT",
          "SHE_Z_B_ZHU": "Definir notas",
          "BIAO_JWCWZ_NONE": "Marcar como artigo longo√",
          "WEI_G_H_GUO": "Consequências da violação",
          "SHE_ZHI": "Configurações",
          "CHI_C_NONE": "Tamanho 2,5:1",
          "XUAN_ZWZL_XING": "Selecione o tipo de artigo",
          "GE_R_Z_LIAO": "Informações pessoais",
          "TUI_W_X_QING": "Detalhes do Freerse",
          "TI_SHI": "Dica",
          "QIAN_BAO": "carteira",
          "ZUI_ZYHXKX_YI": "Contrato de licença do usuário final",
          "DIAN_JI": "Zap",
          "SHAN_D_F_PIAO": "Fatura Relâmpago",
          "SHAN_DQBD_ZHI": "Endereço da Carteira Lightning",
          "CONG": "Cong",
          "SAO_Y_SAO": "Varredura",
          "JIN_ZNRHX_WEI": "Conteúdo e conduta proibidos",
          "YU_DBYGDFFN_RONG": "* Conteúdo ilegal relacionado a jogos de azar;",
          "WO_D_S_CANG": "Minha coleção",
          "XING_Q_SI": "Quinta-feira",
          "QU_XIAO": "Cancelar",
          "BAN_B_NONE": "Versão ",
          "TIAN_JXDZJ_QI": "Adicionar novo repetidor",
          "ZHONG_J_QI": "Repetidor",
          "REN_MEN": "pessoas",
          "QUAN_Q_T_WEN": "Global",
          "ZHENG_C_F_BU": "Liberação normal",
          "COPY_DESC_10":
              "* Conteúdo que infringe os direitos de terceiros, incluindo direitos autorais, marca registrada, privacidade, publicidade ou outros direitos pessoais ou de propriedade, ou é enganoso ou fraudulento;",
          "HUI_FU_2": "Responder:",
          "TIAN_JZYB_JING": "Adicionar plano de fundo da página inicial",
          "TUI_W_LIAN": "Cadeia Freerse",
          "LIAN_X_REN": "Contato",
          "ZHI_FU": "Pagamento",
          "TIE_ZJTBDWZX_SHI":
              "As postagens serão sincronizadas com a exibição do artigo",
          "BAO_LIU_QUANLI":
              "Reservamo-nos o direito de modificar este EULA a qualquer momento sem aviso prévio. Seu uso continuado do Aplicativo após a publicação de qualquer EULA modificado indica sua aceitação dos termos do EULA modificado.",
          "TONG_YBJ_XU": "Concordar e continuar",
          "XING_Q_TIAN": "Domingo",
          "SOU_SUO": "Pesquisar",
          "REN_ZHENG": "Certificação",
          "PRI_DESC":
              "A chave privada é a senha da sua conta. Se você perder sua chave privada, não poderá acessar sua conta! Não há como recuperar a chave privada. Guarde sua chave privada e nunca a divulgue a ninguém . pessoas.",
          "TIAN_JNDW_ZHAN": "Adicione seu site",
          "TUI_WYH_FU": "responder",
          "WEN_ZDYX_XI": "Mensagem de assinatura de artigo",
          "COPY_DESC_12":
              "Este Contrato de Licença de Usuário Final ('EULA') é um acordo legal entre você e a Freerse Inc. em relação ao uso do aplicativo móvel Freerse. Ao instalar, acessar ou usar nosso Aplicativo, você concorda em ficar vinculado pelos termos deste EULA Termos e Condições. Se você não concordar com este EULA, você não poderá usar nosso aplicativo.",
          "TIAN_XNDZHS_YUE": "Preencha a chave privada da sua conta",
          "CHUANG_J_Z_HU": "Criar",
          "QING_XTYX_YI": "Por favor, concorde com o acordo primeiro",
          "TIAN_JDSC_JIA": "Adicionar aos Favoritos",
          "XING_Q_SAN": "Quarta-feira",
          "FU_ZYHG_YUE": "Copiar chave pública do ID do usuário",
          "WANG_ZHAN": "Site",
          "LA_HCY_HU": "Bloquear este usuário",
          "SOU_S_NONE": "Pesquisar Freeres",
          "XING_Q_YI": "Segunda-feira",
          "ZHANG_HG_YUE": "Chave pública do ID da conta",
          "YI_YDBT_YI": "Ler e concordar",
          "WO_YJBCLWDMMS_YUE": "Salvei minha chave privada de senha",
          "SHOU_F_KUAN": "Pagamento",
          "FU_Z_W_BEN": "Copiar texto",
          "GONG_YUE": "Chave pública",
          "COPY_DESC_11":
              "Nossos aplicativos são fornecidos 'como estão' e 'conforme disponíveis' sem garantia de qualquer tipo, expressa ou implícita, incluindo, mas não se limitando a, garantias implícitas de comercialização e adequação a uma finalidade específica. Nós fazemos isso não garante que nossos Aplicativos O programa será ininterrupto ou livre de erros. Sob nenhuma circunstância a Freerse Inc. será responsável por quaisquer danos de qualquer tipo decorrentes de ou relacionados ao uso ou incapacidade de usar nosso aplicativo, incluindo, mas não limitado a danos diretos, indiretos, especiais, incidentais ou consequenciais.",
          "ZUO_TIAN": "Ontem",
          "DAI_YQSXSDBLXYCHY_LUN":
              "* Discriminação, incitação à violência e promoção de discurso de ódio;",
          "NIN_TYBJYYJZDNRHXWBKDBX_YU":
              "Você concorda em não usar o Freerse para conteúdo ou conduta proibida, incluindo, mas não se limitando a",
          "TIAN_J_F_WU": "Adicionar serviço",
          "SHUO_DSM_BA": "Diga alguma coisa...",
          "FEN_SI": "Fãs",
          "BIAN_JGRZ_LIAO": "Editar informações",
          "BANG_Z_Z_XIN": "Central de Ajuda",
          "KAI_SHI": "Iniciar",
          "YIN_HSQMFFBZSBLHHFFNRHX_DU":
              "* Conteúdo obsceno, pornográfico, ofensivo, difamatório, calunioso, violento e/ou ilegal ou palavrões;",
          "ZI_L_S_ZHI": "Configurações de dados",
          "ZXQ_DI_QI":
              "Os pontos verdes na primeira linha representam a intensidade do sinal de rede do repetidor. Verde significa sinal suave e vermelho significa sinal fraco. Os ícones na segunda linha com o ícone Bitcoin são repetidores pagos. ",
          "TIAN_S_RU": "Entrada TIAN",
          "ZHU_YBJ_TU": "Imagem de fundo da página inicial",
          "FU_ZYHGY_NONE": "Copiar a chave pública Pubkey do usuário",
          "CONG_ZLKSXZ_WEN": "Comece a escrever o texto a partir daqui",
          "DIAN_ZAN": "Curtir",
          "XIAO_SHI": "hora",
          "GUAN_Y_WO": "Sobre mim",
          "ZHAO_PIAN": "Foto",
          "BAO_CNDS_YUE": "Salve sua chave privada",
          "BIAO_ZWCW_ZHANG": "Marcar como artigo longo",
          "MIAO": "segundos",
          "TUI_WEN": "Freerse",
          "YU_LAN": "Visualização",
          "QU_X_L_HEI": "Cancelar lista negra",
          "RU_GNDCYRHYWQTGYWML_XI":
              "Se você tiver alguma dúvida sobre este EULA, entre em contato conosco em freerse8@gmail.com.",
          "TIAN_JNDYH_MING": "Adicione seu nome de usuário",
          "JIE_S_T_KUAN": "Aceitar termos",
          "BIAO_JWTW_NONE": "Liberação normal",
          "ZHI_D_L_TIAN": "Bate-papo principal",
          "JIE_SHOU": "Aceitar",
          "GUAN_ZHU": "Seguir",
          "MING_ZI": "nome",
          "HUI_FU": "Responder",
          "LISENCE_ACCEPT_DESC1":
              "Ao usar nosso aplicativo, você aceita este EULA. Se você não concordar com este EULA, você não poderá usar nosso aplicativo.",
          "QING_XQRYJBCMMS_YUE":
              "Por favor, confirme se a senha da chave privada foi salva primeiro",
          "XIAO_XI": "Mensagem",
          "LIAN_X_F_SHI": "Informações de contato",
          "BA_TTJGP_YOU": "Recomende-o para amigos",
          "TIAN_J_C_GONG": "Adicionado com sucesso!",
          "TIE_ZI": "Freerse",
          "ZHUAN_FA": "Avançar",
          "FA_XIAN": "Descobrir",
          "GUAN_Y_NONE": "Sobre o Freerse",
          "XIN_D_P_YOU": "Novos amigos",
          "GONG_YSNGZ_NI":
              "A chave pública é o ID da sua conta. Você pode copiá-la e enviá-la para seus amigos, que podem pesquisar e segui-lo através da chave pública.",
          "BIAN_G_NONE": "Alterar EULA",
          "NIP_AUTH": "Autenticação NIP-05",
          "JUBAO": "Relatório",
          "JUBAO_OK": "Relatório bem sucedido",
          "JUBAO_LJ": "Conteúdo lixo",
          "JUBAO_LT": "Nudez ou conteúdo explícito",
          "JUBAO_WG": "Conteúdo ilegal",
          "DELETE_ACCOUNT": "Excluir conta",
          "DELETE_ACCOUNT_TIP":
              "Você excluirá as informações da sua conta e perderá todas as informações da sua conta. Tem certeza de que deseja continuar excluindo a sua conta?",
          "SHOW_MORE": "Mostrar mais",
          "ZAP_WALLET": "Carteira Relâmpago",
          "IMAGEM": "imagem",
          "ZAP_CONNECT_TIP":
              "Cole ou insira a chave pública, Relay e o segredo do Wallet Connect. Somente carteiras adaptadas ao protocolo Nostr Wallet Connect são suportadas.",
          "PASTE_OR_ENTER_HERE": "Por favor, cole ou digite aqui",
          "PASTE": "Colar",
          "CLEAR": "CLEAR",
          "CONNECT_WALLET": "Conectar carteira",
          "SCAN_QR_CODE": "Ler código QR",
          "CONNECT_OTHER_WALLETS": "Conectar outras carteiras",
          "OTHER_AMOUNT": "Outro valor",
          "PLEASE_INPUT_AMOUNT": "Por favor insira a quantidade",
          "MENSAGEM": "Mensagem",
          "PLEASE_INPUT_MESSAGE": "Por favor insira uma mensagem",
          "CONFIRMAR": "OK",
          "DEFAULT_ZAP_AMOUNT_IN_SATS": "Valor Zap padrão, em sats.",
          "ZAP_AMOUNT_TIP":
              "1 Bitcoin = 100.000.000 sats, clique em Zap para enviar o valor padrão, pressione longamente o botão Zap para enviar um valor personalizado.",
          "SET_CUSTOM_ZAP_AMOUNT": "Definir um valor Zap personalizado",
          "RESTORE_DEFAULT_SETTINGS": "Restaurar configurações padrão",
          "ZAP_AMOUNT_SETTINGS": "Configurações de quantidade de Zap",
          "BITCOIN_LIGHTNING_WALLET": "Carteira Bitcoin Lightning",
          "ZAP_RECEIVE_SEND_TIP":
              "Para enviar e receber Zap, conecte uma carteira Bitcoin Lightning.",
          "ZAP_DES":
              "Zap usa Bitcoin para recompensar postagens que você gosta.",
          "ALBY_BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "Alby Bitcoin Lightning Wallet está conectada",
          "BITCOIN_LIGHTNING_WALLET_IS_CONNECTED":
              "A carteira Bitcoin Lightning está conectada",
          "DISCONNECT_WALLET": "Desconectar carteira",
          "CONNECT_ALBY_WALLET": "Conectar carteira Alby",
          "DISCONNECT_TIP":
              "A carteira desconectada não poderá enviar zap. Este endereço de carteira também pode receber zap. Se você precisar modificar o endereço da carteira, modifique-o em suas informações pessoais.",
          "ZAP_SENDING": "Envio de Zap",
          "NO_WALLET_WAS_FOUND": "Carteira não encontrada.",
          "THIS_ACCOUNT_DOES_NOT_HAVE_A_WALLET_ADDRESS_SET":
              "Esta conta não possui um endereço de carteira definido.",
          "CITAÇÃO": "Citação",
          "DOAR": "Doar",
          "DONATE_DES1": "Apoie Freerse",
          "DONATE_DES2": "Ajude a construir redes sociais descentralizadas.",
          "RETWEETED": "Retweetado",
          "ZAPED": "ZAPED",
          "REAGIDO": "Gostei",
          "AND": "And",
          "OUTROS": "Outros",
          "YOUR_FREERSE": "seu freerse",
          "VOCÊ": "você",
          "H_Y_S_Q_X_X": "Mensagem de aplicação de amigo",
          "SAVE_IMAGE_SUCCESS": "Salvo no álbum",
          "CARREGANDO": "Carregando",
          "FAILED_TO_SEND": "Falha no envio",
          "THANKS_DONATE": "Obrigado por doar",
          "ZAP_FAIL": "Zap falhou",
          "DONATE1_NAME": "Freerse Doe 1",
          "DONATE2_NAME": "Freerse Doe 2",
          "DONATE3_NAME": "Freerse Doe 3",
          "DONATE4_NAME": "Freerse Doe 4",
          "CÓPIA": "Copiar",
          "HOT": "quente"
        },
      };
}
